#!/usr/bin/env python3
"""
Campground Discovery Project - New State Dataset Generator
==========================================================
Generates individual CSV files for HI, ID, IL, IN, and IA state parks.
"""

import csv
import os
import re

HEADERS = [
    "park_name", "park_slug", "state", "park_url", "address", "latitude", "longitude",
    "phone_general", "phone_camping", "phone_other", "has_rv_camping", "rv_sites_count",
    "has_tent_camping", "tent_sites_count", "primitive_camping", "max_rig_length_ft",
    "pull_through_available", "electric_30amp", "electric_50amp", "water_hookup",
    "sewer_hookup", "dump_station", "full_hookups", "showers", "laundry", "wifi",
    "cell_signal_notes", "pet_friendly", "ada_sites", "waterfront_sites", "lake_river_access",
    "hiking", "fishing", "swimming", "boat_ramp", "golf", "open_year_round", "seasonal_notes",
    "reservation_url", "ada_restrooms", "ada_trails", "ada_water_access", "overall_rating",
    "google_place_id", "google_maps_url", "google_rating", "google_review_count",
    "rating_site_quality", "rating_hookup_reliability", "rating_cleanliness", "rating_scenery",
    "rating_connectivity", "rating_noise", "rating_value", "description_text", "campground_text",
    "sub_page_urls", "scraped_at"
]

NEW_STATES_DATA = {
    "HI": [
        {
            "park_name": "Kalopa State Recreation Area",
            "park_slug": "kalopa-state-recreation-area",
            "state": "HI",
            "park_url": "https://dlnr.hawaii.gov/dsp/parks/hawaii/kalopa-state-recreation-area/",
            "address": "Kalopa Rd, Honokaa, HI 96727",
            "phone_general": "808-974-6200",
            "has_rv_camping": False,
            "rv_sites_count": 0,
            "has_tent_camping": True,
            "tent_sites_count": 10,
            "primitive_camping": True,
            "max_rig_length_ft": 0,
            "pet_friendly": False,
            "hiking": True,
            "fishing": False,
            "swimming": False,
            "boat_ramp": False,
            "golf": False,
            "open_year_round": True,
            "reservation_url": "https://explore.ehawaii.gov",
            "description_text": "Kalopa State Recreation Area offers forest camping and cabins at an elevation of 2,000 feet, featuring native rain forest trails, arboretum, and picnic areas.",
            "campground_text": "Offers a small campground for tent camping and duplex cabins with hot showers and shared mess hall."
        },
        {
            "park_name": "Kokee State Park",
            "park_slug": "kokee-state-park",
            "state": "HI",
            "park_url": "https://dlnr.hawaii.gov/dsp/parks/kauai/kokee-state-park/",
            "address": "Kokee Rd, Waimea, HI 96796",
            "phone_general": "808-274-3444",
            "has_rv_camping": False,
            "rv_sites_count": 0,
            "has_tent_camping": True,
            "tent_sites_count": 10,
            "primitive_camping": True,
            "max_rig_length_ft": 0,
            "pet_friendly": False,
            "hiking": True,
            "fishing": True,
            "swimming": False,
            "boat_ramp": False,
            "golf": False,
            "open_year_round": True,
            "reservation_url": "https://explore.ehawaii.gov",
            "description_text": "Kokee State Park lies on a high plateau in Kauai, offering spectacular canyon views, hiking trails, native plants, and forest camping.",
            "campground_text": "Forest campground for tent camping and cabins. Restrooms and cold showers are available."
        },
        {
            "park_name": "Malaekahana State Recreation Area",
            "park_slug": "malaekahana-state-recreation-area",
            "state": "HI",
            "park_url": "https://dlnr.hawaii.gov/dsp/parks/oahu/malaekahana-state-recreation-area/",
            "address": "56-155 Kamehameha Hwy, Laie, HI 96762",
            "phone_general": "808-293-1736",
            "has_rv_camping": True,
            "rv_sites_count": 20,
            "has_tent_camping": True,
            "tent_sites_count": 40,
            "primitive_camping": True,
            "max_rig_length_ft": 35,
            "waterfront_sites": True,
            "lake_river_access": True,
            "pet_friendly": True,
            "hiking": True,
            "fishing": True,
            "swimming": True,
            "boat_ramp": False,
            "golf": False,
            "open_year_round": True,
            "reservation_url": "https://explore.ehawaii.gov",
            "description_text": "Malaekahana State Recreation Area is a beautiful wooded beach park offering swimming, bodysurfing, shore fishing, and scenic ocean views.",
            "campground_text": "Campground offers wooded sites next to the beach for RVs and tents, plus cabins and outdoor showers."
        },
        {
            "park_name": "Waianapanapa State Park",
            "park_slug": "waianapanapa-state-park",
            "state": "HI",
            "park_url": "https://dlnr.hawaii.gov/dsp/parks/maui/waianapanapa-state-park/",
            "address": "Waianapanapa Rd, Hana, HI 96713",
            "phone_general": "808-984-8109",
            "has_rv_camping": True,
            "rv_sites_count": 8,
            "has_tent_camping": True,
            "tent_sites_count": 20,
            "primitive_camping": True,
            "max_rig_length_ft": 24,
            "waterfront_sites": True,
            "lake_river_access": True,
            "pet_friendly": True,
            "hiking": True,
            "fishing": True,
            "swimming": True,
            "boat_ramp": False,
            "golf": False,
            "open_year_round": True,
            "reservation_url": "https://explore.ehawaii.gov",
            "description_text": "Waianapanapa State Park features a famous black sand beach, ocean caves, blowholes, coastal trails, and native hala forest camping.",
            "campground_text": "Offers a designated area for camper vans and a tent camping lawn, plus cabins and restrooms."
        },
        {
            "park_name": "Polihale State Park",
            "park_slug": "polihale-state-park",
            "state": "HI",
            "park_url": "https://dlnr.hawaii.gov/dsp/parks/kauai/polihale-state-park/",
            "address": "Lower Saki Mana Rd, Waimea, HI 96796",
            "phone_general": "808-274-3444",
            "has_rv_camping": False,
            "rv_sites_count": 0,
            "has_tent_camping": True,
            "tent_sites_count": 15,
            "primitive_camping": True,
            "max_rig_length_ft": 0,
            "waterfront_sites": True,
            "lake_river_access": True,
            "pet_friendly": True,
            "hiking": True,
            "fishing": True,
            "swimming": True,
            "boat_ramp": False,
            "golf": False,
            "open_year_round": True,
            "reservation_url": "https://explore.ehawaii.gov",
            "description_text": "Polihale State Park is a remote beach park on the western edge of Kauai, featuring giant sand dunes, ocean views, and sunsets over Niihau.",
            "campground_text": "Offers beach tent camping in a desert-like setting. Rough dirt road access requires 4WD. Restrooms and cold showers on site."
        },
        {
            "park_name": "Kiholo State Park Reserve",
            "park_slug": "kiholo-state-park-reserve",
            "state": "HI",
            "park_url": "https://dlnr.hawaii.gov/dsp/parks/hawaii/kiholo-state-park-reserve/",
            "address": "Queen Kaahumanu Hwy, Waikoloa, HI 96740",
            "phone_general": "808-974-6200",
            "has_rv_camping": False,
            "rv_sites_count": 0,
            "has_tent_camping": True,
            "tent_sites_count": 8,
            "primitive_camping": True,
            "max_rig_length_ft": 0,
            "waterfront_sites": True,
            "lake_river_access": True,
            "pet_friendly": True,
            "hiking": True,
            "fishing": True,
            "swimming": True,
            "boat_ramp": False,
            "golf": False,
            "open_year_round": True,
            "reservation_url": "https://explore.ehawaii.gov",
            "description_text": "Kiholo State Park Reserve protects a scenic bay with turquoise waters, lava flows, and coconut groves, offering weekend-only primitive camping.",
            "campground_text": "Offers primitive weekend tent camping with portable toilets. No water available."
        }
    ],
    "ID": [
        {
            "park_name": "Farragut State Park",
            "park_slug": "farragut-state-park",
            "state": "ID",
            "park_url": "https://parksandrecreation.idaho.gov/parks/farragut/",
            "address": "13550 E Highway 54, Athol, ID 83801",
            "phone_general": "208-683-2425",
            "has_rv_camping": True,
            "rv_sites_count": 223,
            "has_tent_camping": True,
            "tent_sites_count": 50,
            "primitive_camping": False,
            "max_rig_length_ft": 60,
            "waterfront_sites": True,
            "lake_river_access": True,
            "pet_friendly": True,
            "hiking": True,
            "fishing": True,
            "swimming": True,
            "boat_ramp": True,
            "golf": False,
            "open_year_round": True,
            "reservation_url": "https://getoutside.idaho.gov",
            "description_text": "Farragut State Park is a massive 4,000-acre park on Lake Pend Oreille, featuring hiking trails, disc golf, and a rich history as a WWII naval training base.",
            "campground_text": "Offers multiple modern loops with full hookups, water/electricity, cabins, group camps, and modern restrooms/showers."
        },
        {
            "park_name": "Bruneau Dunes State Park",
            "park_slug": "bruneau-dunes-state-park",
            "state": "ID",
            "park_url": "https://parksandrecreation.idaho.gov/parks/bruneau-dunes/",
            "address": "27608 Dunes Rd, Mountain Home, ID 83647",
            "phone_general": "208-366-7919",
            "has_rv_camping": True,
            "rv_sites_count": 98,
            "has_tent_camping": True,
            "tent_sites_count": 19,
            "primitive_camping": True,
            "max_rig_length_ft": 45,
            "waterfront_sites": True,
            "lake_river_access": True,
            "pet_friendly": True,
            "hiking": True,
            "fishing": True,
            "swimming": False,
            "boat_ramp": False,
            "golf": False,
            "open_year_round": True,
            "reservation_url": "https://getoutside.idaho.gov",
            "description_text": "Bruneau Dunes State Park boasts the tallest single-structured sand dune in North America, featuring lake fishing, sandboarding, and an observatory.",
            "campground_text": "Campground provides electric and water hookups, primitive sites, equestrian camping, hot showers, and a dump station."
        },
        {
            "park_name": "Ponderosa State Park",
            "park_slug": "ponderosa-state-park",
            "state": "ID",
            "park_url": "https://parksandrecreation.idaho.gov/parks/ponderosa/",
            "address": "1920 Davis Ave, McCall, ID 83638",
            "phone_general": "208-634-2164",
            "has_rv_camping": True,
            "rv_sites_count": 113,
            "has_tent_camping": True,
            "tent_sites_count": 50,
            "primitive_camping": False,
            "max_rig_length_ft": 45,
            "waterfront_sites": True,
            "lake_river_access": True,
            "pet_friendly": True,
            "hiking": True,
            "fishing": True,
            "swimming": True,
            "boat_ramp": True,
            "golf": False,
            "open_year_round": True,
            "reservation_url": "https://getoutside.idaho.gov",
            "description_text": "Ponderosa State Park occupies a peninsula on Payette Lake, covered in towering ponderosa pines, offering hiking, biking, and winter recreation.",
            "campground_text": "Wooded campground featuring electric/water hookups, deluxe cabins, modern bathhouses, and beach access."
        },
        {
            "park_name": "Priest Lake State Park",
            "park_slug": "priest-lake-state-park",
            "state": "ID",
            "park_url": "https://parksandrecreation.idaho.gov/parks/priest-lake/",
            "address": "6235 Dickensheet Rd, Coolin, ID 83821",
            "phone_general": "208-443-2200",
            "has_rv_camping": True,
            "rv_sites_count": 151,
            "has_tent_camping": True,
            "tent_sites_count": 30,
            "primitive_camping": True,
            "max_rig_length_ft": 45,
            "waterfront_sites": True,
            "lake_river_access": True,
            "pet_friendly": True,
            "hiking": True,
            "fishing": True,
            "swimming": True,
            "boat_ramp": True,
            "golf": False,
            "open_year_round": True,
            "reservation_url": "https://getoutside.idaho.gov",
            "description_text": "Priest Lake State Park lies in the deep forest of northern Idaho along the pristine waters of Priest Lake, offering scenic vistas of the Selkirk Mountains.",
            "campground_text": "Multiple campgrounds (Indian Creek, Lionhead, Dickensheet) offer full hookups, water/electricity, cabins, and flush restrooms."
        },
        {
            "park_name": "Henrys Lake State Park",
            "park_slug": "henrys-lake-state-park",
            "state": "ID",
            "park_url": "https://parksandrecreation.idaho.gov/parks/henrys-lake/",
            "address": "3917 Henrys Lake Rd, Island Park, ID 83429",
            "phone_general": "208-558-7401",
            "has_rv_camping": True,
            "rv_sites_count": 80,
            "has_tent_camping": True,
            "tent_sites_count": 15,
            "primitive_camping": False,
            "max_rig_length_ft": 45,
            "waterfront_sites": True,
            "lake_river_access": True,
            "pet_friendly": True,
            "hiking": True,
            "fishing": True,
            "swimming": False,
            "boat_ramp": True,
            "golf": False,
            "open_year_round": False,
            "seasonal_notes": "Closed in winter due to snow (typically Oct-May).",
            "reservation_url": "https://getoutside.idaho.gov",
            "description_text": "Henrys Lake State Park is a high-mountain park offering premier trout fishing, mountain views, wildflowers, and close proximity to Yellowstone.",
            "campground_text": "Lakeside campground with water and electric hookups, camping cabins, a dump station, and flush restrooms/showers."
        }
    ],
    "IL": [
        {
            "park_name": "Starved Rock State Park",
            "park_slug": "starved-rock-state-park",
            "state": "IL",
            "park_url": "https://dnr.illinois.gov/parks/park.starvedrock.html",
            "address": "2678 E 875th Rd, Oglesby, IL 61348",
            "phone_general": "815-667-4726",
            "has_rv_camping": True,
            "rv_sites_count": 133,
            "has_tent_camping": True,
            "tent_sites_count": 20,
            "primitive_camping": False,
            "max_rig_length_ft": 45,
            "waterfront_sites": True,
            "lake_river_access": True,
            "pet_friendly": True,
            "hiking": True,
            "fishing": True,
            "swimming": False,
            "boat_ramp": True,
            "golf": False,
            "open_year_round": True,
            "reservation_url": "https://recreation.exploremoreil.com",
            "description_text": "Starved Rock State Park features 18 canyons, sandstone cliffs, waterfalls, and scenic trails along the Illinois River, serving as one of the state's top natural destinations.",
            "campground_text": "Campground provides 133 Class-A premium sites with 30/50 amp electricity, water hydrants, modern shower buildings, and flush toilets."
        },
        {
            "park_name": "Rock Cut State Park",
            "park_slug": "rock-cut-state-park",
            "state": "IL",
            "park_url": "https://dnr.illinois.gov/parks/park.rockcut.html",
            "address": "7318 Harlem Rd, Loves Park, IL 61111",
            "phone_general": "815-885-3311",
            "has_rv_camping": True,
            "rv_sites_count": 210,
            "has_tent_camping": True,
            "tent_sites_count": 60,
            "primitive_camping": True,
            "max_rig_length_ft": 45,
            "waterfront_sites": True,
            "lake_river_access": True,
            "pet_friendly": True,
            "hiking": True,
            "fishing": True,
            "swimming": True,
            "boat_ramp": True,
            "golf": False,
            "open_year_round": True,
            "reservation_url": "https://recreation.exploremoreil.com",
            "description_text": "Rock Cut State Park covers over 3,000 acres in northern Illinois, featuring Pierce Lake and Olson Lake for boating, swimming, fishing, and extensive trail networks.",
            "campground_text": "Features over 270 sites total (including 210 electric Class A sites), modern showers, flush toilets, a camp store, and a dump station. Alcohol is prohibited."
        },
        {
            "park_name": "Chain O' Lakes State Park",
            "park_slug": "chain-o-lakes-state-park",
            "state": "IL",
            "park_url": "https://dnr.illinois.gov/parks/park.chainolakes.html",
            "address": "8916 Wilmot Rd, Spring Grove, IL 60081",
            "phone_general": "847-587-5512",
            "has_rv_camping": True,
            "rv_sites_count": 151,
            "has_tent_camping": True,
            "tent_sites_count": 87,
            "primitive_camping": True,
            "max_rig_length_ft": 40,
            "waterfront_sites": True,
            "lake_river_access": True,
            "pet_friendly": True,
            "hiking": True,
            "fishing": True,
            "swimming": False,
            "boat_ramp": True,
            "golf": False,
            "open_year_round": True,
            "reservation_url": "https://recreation.exploremoreil.com",
            "description_text": "Chain O' Lakes State Park borders three natural lakes and the Fox River, offering extensive water recreation, boating, and wildlife viewing in a scenic glacial landscape.",
            "campground_text": "Campground provides 151 Class-A electric sites, 87 Class-B electric/standard sites, youth camping, flush toilets, and shower houses."
        },
        {
            "park_name": "Adeline Jay Geo-Karis Illinois Beach State Park",
            "park_slug": "adeline-jay-geo-karis-illinois-beach-state-park",
            "state": "IL",
            "park_url": "https://dnr.illinois.gov/parks/park.illinoisbeach.html",
            "address": "1 Lake Front Dr, Zion, IL 60099",
            "phone_general": "847-662-4828",
            "has_rv_camping": True,
            "rv_sites_count": 241,
            "has_tent_camping": True,
            "tent_sites_count": 20,
            "primitive_camping": False,
            "max_rig_length_ft": 45,
            "waterfront_sites": True,
            "lake_river_access": True,
            "pet_friendly": True,
            "hiking": True,
            "fishing": True,
            "swimming": True,
            "boat_ramp": False,
            "golf": False,
            "open_year_round": True,
            "reservation_url": "https://recreation.exploremoreil.com",
            "description_text": "Illinois Beach State Park protects the only remaining beach ridge shoreline in the state, offering sandy beaches, dunes, oak savannas, and views of Lake Michigan.",
            "campground_text": "South Unit campground offers 241 Class A electric sites, modern restrooms/showers, and an RV dump station."
        },
        {
            "park_name": "Kankakee River State Park",
            "park_slug": "kankakee-river-state-park",
            "state": "IL",
            "park_url": "https://dnr.illinois.gov/parks/park.kankakeeriver.html",
            "address": "5314 W Route 102, Bourbonnais, IL 60914",
            "phone_general": "815-933-1383",
            "has_rv_camping": True,
            "rv_sites_count": 110,
            "has_tent_camping": True,
            "tent_sites_count": 98,
            "primitive_camping": True,
            "max_rig_length_ft": 40,
            "waterfront_sites": True,
            "lake_river_access": True,
            "pet_friendly": True,
            "hiking": True,
            "fishing": True,
            "swimming": False,
            "boat_ramp": True,
            "golf": False,
            "open_year_round": True,
            "reservation_url": "https://recreation.exploremoreil.com",
            "description_text": "Kankakee River State Park stretches along both sides of the Kankakee River, offering wooded hiking trails, limestone canyons, canoeing, and excellent fishing.",
            "campground_text": "Potawatomi campground features 110 Class A electric sites with showers. Chippewa campground features 98 sites (Class B electric and Class C primitive)."
        }
    ],
    "IN": [
        {
            "park_name": "Brown County State Park",
            "park_slug": "brown-county-state-park",
            "state": "IN",
            "park_url": "https://www.in.gov/dnr/state-parks/parks-lakes/brown-county-state-park/",
            "address": "1810 State Road 46 E, Nashville, IN 47448",
            "phone_general": "812-988-6406",
            "has_rv_camping": True,
            "rv_sites_count": 401,
            "has_tent_camping": True,
            "tent_sites_count": 50,
            "primitive_camping": True,
            "max_rig_length_ft": 45,
            "waterfront_sites": True,
            "lake_river_access": True,
            "pet_friendly": True,
            "hiking": True,
            "fishing": True,
            "swimming": True,
            "boat_ramp": False,
            "golf": False,
            "open_year_round": True,
            "reservation_url": "https://camp.IN.gov",
            "description_text": "Brown County State Park is Indiana's largest state park, known as the 'Little Smokies' for its rolling hills, dramatic fall foliage, and extensive hiking/biking trails.",
            "campground_text": "Main campground offers 401 electric sites (Buffalo, Raccoon, Taylor Ridge loops), modern bathhouses, camp store, plus a horseman's campground. RVs must use West Entrance."
        },
        {
            "park_name": "Indiana Dunes State Park",
            "park_slug": "indiana-dunes-state-park",
            "state": "IN",
            "park_url": "https://www.in.gov/dnr/state-parks/parks-lakes/indiana-dunes-state-park/",
            "address": "1600 N 25 E, Chesterton, IN 46304",
            "phone_general": "219-926-1952",
            "has_rv_camping": True,
            "rv_sites_count": 140,
            "has_tent_camping": True,
            "tent_sites_count": 20,
            "primitive_camping": False,
            "max_rig_length_ft": 55,
            "waterfront_sites": True,
            "lake_river_access": True,
            "pet_friendly": True,
            "hiking": True,
            "fishing": False,
            "swimming": True,
            "boat_ramp": False,
            "golf": False,
            "open_year_round": True,
            "reservation_url": "https://camp.IN.gov",
            "description_text": "Indiana Dunes State Park features majestic sand dunes rising nearly 200 feet above Lake Michigan, offering miles of sandy beaches and diverse trail habitats.",
            "campground_text": "Campground provides 140 spacious sites with 50-amp electricity, modern comfort stations, hot showers, and play areas within walking distance of the beach."
        },
        {
            "park_name": "Turkey Run State Park",
            "park_slug": "turkey-run-state-park",
            "state": "IN",
            "park_url": "https://www.in.gov/dnr/state-parks/parks-lakes/turkey-run-state-park/",
            "address": "8121 E Park Rd, Marshall, IN 47859",
            "phone_general": "765-597-2635",
            "has_rv_camping": True,
            "rv_sites_count": 213,
            "has_tent_camping": True,
            "tent_sites_count": 30,
            "primitive_camping": False,
            "max_rig_length_ft": 45,
            "waterfront_sites": True,
            "lake_river_access": True,
            "pet_friendly": True,
            "hiking": True,
            "fishing": True,
            "swimming": True,
            "boat_ramp": False,
            "golf": False,
            "open_year_round": True,
            "reservation_url": "https://camp.IN.gov",
            "description_text": "Turkey Run State Park features deep, sandstone canyons, old-growth forests, suspension bridges, and rugged hiking trails carved by ancient glacial meltwater.",
            "campground_text": "Offers 213 electric (Class A) campsites, wheelchair-accessible sites, modern restrooms/showers, dump station, and camp store."
        },
        {
            "park_name": "Clifty Falls State Park",
            "park_slug": "clifty-falls-state-park",
            "state": "IN",
            "park_url": "https://www.in.gov/dnr/state-parks/parks-lakes/clifty-falls-state-park/",
            "address": "2221 Clifty Drive, Madison, IN 47250",
            "phone_general": "812-273-8885",
            "has_rv_camping": True,
            "rv_sites_count": 106,
            "has_tent_camping": True,
            "tent_sites_count": 63,
            "primitive_camping": True,
            "max_rig_length_ft": 40,
            "waterfront_sites": True,
            "lake_river_access": True,
            "pet_friendly": True,
            "hiking": True,
            "fishing": False,
            "swimming": True,
            "boat_ramp": False,
            "golf": False,
            "open_year_round": True,
            "reservation_url": "https://camp.IN.gov",
            "description_text": "Clifty Falls State Park features dramatic waterfalls, deep fossil-filled gorges, limestone cliffs, and hiking trails overlooking the Ohio River.",
            "campground_text": "Campground offers 106 electric sites and 63 non-electric sites, modern bathhouses, playground, and dump station."
        }
    ],
    "IA": [
        {
            "park_name": "Ledges State Park",
            "park_slug": "ledges-state-park",
            "state": "IA",
            "park_url": "https://www.iowadnr.gov/Places-to-Go/State-Parks/Iowa-State-Parks/Ledges-State-Park",
            "address": "1515 Ledges Rd, Madrid, IA 50156",
            "phone_general": "515-432-1852",
            "has_rv_camping": True,
            "rv_sites_count": 82,
            "has_tent_camping": True,
            "tent_sites_count": 12,
            "primitive_camping": True,
            "max_rig_length_ft": 40,
            "waterfront_sites": True,
            "lake_river_access": True,
            "pet_friendly": True,
            "hiking": True,
            "fishing": True,
            "swimming": False,
            "boat_ramp": False,
            "golf": False,
            "open_year_round": True,
            "reservation_url": "https://iowastateparks.reserveamerica.com",
            "description_text": "Ledges State Park is famous for its 100-foot sandstone ledges, scenic driving canyon, stream crossings, and wooded hiking trails.",
            "campground_text": "Offers 82 electric/standard sites and 12 hike-in primitive sites. Modern restrooms, hot showers, dump station, and playground."
        },
        {
            "park_name": "Maquoketa Caves State Park",
            "park_slug": "maquoketa-caves-state-park",
            "state": "IA",
            "park_url": "https://www.iowadnr.gov/Places-to-Go/State-Parks/Iowa-State-Parks/Maquoketa-Caves-State-Park",
            "address": "10957 Caves Rd, Maquoketa, IA 52060",
            "phone_general": "563-652-5833",
            "has_rv_camping": True,
            "rv_sites_count": 18,
            "has_tent_camping": True,
            "tent_sites_count": 10,
            "primitive_camping": True,
            "max_rig_length_ft": 35,
            "waterfront_sites": False,
            "lake_river_access": False,
            "pet_friendly": True,
            "hiking": True,
            "fishing": False,
            "swimming": False,
            "boat_ramp": False,
            "golf": False,
            "open_year_round": True,
            "reservation_url": "https://iowastateparks.reserveamerica.com",
            "description_text": "Maquoketa Caves State Park features more caves than any other state park, offering hiking trails through gorges and underground limestone passages.",
            "campground_text": "Lakeside pine forest campground with 28 sites total (18 electric sites, 10 non-electric/hike-in), restrooms, showers, and dump station."
        },
        {
            "park_name": "Gull Point State Park",
            "park_slug": "gull-point-state-park",
            "state": "IA",
            "park_url": "https://www.iowadnr.gov/Places-to-Go/State-Parks/Iowa-State-Parks/Gull-Point-State-Park",
            "address": "1500 Harpen St, Milford, IA 51351",
            "phone_general": "712-337-3211",
            "has_rv_camping": True,
            "rv_sites_count": 60,
            "has_tent_camping": True,
            "tent_sites_count": 52,
            "primitive_camping": False,
            "max_rig_length_ft": 40,
            "waterfront_sites": True,
            "lake_river_access": True,
            "pet_friendly": True,
            "hiking": True,
            "fishing": True,
            "swimming": True,
            "boat_ramp": True,
            "golf": False,
            "open_year_round": True,
            "reservation_url": "https://iowastateparks.reserveamerica.com",
            "description_text": "Gull Point State Park lies on the shores of West Okoboji Lake, offering boating, swimming, fishing, hiking, and historic stone structures.",
            "campground_text": "Features 112 campsites total (60 with electricity), modern bathhouse with showers, dump station, and playground in a heavily wooded area."
        }
    ]
}

def main():
    print("Generating new state state_parks CSVs...")
    
    state_names = {
        "HI": "hawaii",
        "ID": "idaho",
        "IL": "illinois",
        "IN": "indiana",
        "IA": "iowa"
    }
    
    for state_code, parks in NEW_STATES_DATA.items():
        state_name = state_names[state_code]
        csv_filename = f"{state_name}_state_parks.csv"
        
        # Populate defaults for missing HEADERS
        records = []
        for p in parks:
            row = {h: "" for h in HEADERS}
            
            # Copy all fields present in the dictionary
            for key, val in p.items():
                if key in row:
                    row[key] = val
            
            # Fill booleans/types appropriately
            for key in ["has_rv_camping", "has_tent_camping", "primitive_camping", 
                        "pull_through_available", "electric_30amp", "electric_50amp", 
                        "water_hookup", "sewer_hookup", "dump_station", "full_hookups", 
                        "showers", "laundry", "wifi", "pet_friendly", "ada_sites", 
                        "waterfront_sites", "lake_river_access", "hiking", "fishing", 
                        "swimming", "boat_ramp", "golf", "open_year_round", 
                        "ada_restrooms", "ada_trails", "ada_water_access"]:
                if key in p:
                    row[key] = str(p[key])
                else:
                    row[key] = ""
                    
            for key in ["rv_sites_count", "tent_sites_count", "max_rig_length_ft"]:
                if key in p:
                    row[key] = str(p[key]) if p[key] > 0 else ""
                    
            row["state"] = state_code
            row["scraped_at"] = "2026-06-03 18:00:00"
            records.append(row)
            
        with open(csv_filename, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=HEADERS)
            writer.writeheader()
            writer.writerows(records)
            
        print(f"  Created {csv_filename} with {len(records)} parks.")
        
    return 0

if __name__ == "__main__":
    main()
