#!/usr/bin/env python3
"""
Florida State Parks Scraper
==========================
Defines all Florida State Parks offering camping (exactly matching the official 
camping list under experiences:242) plus notable day-use parks.
Outputs a CSV file with amenity data.

Usage:
    python3 scrape_florida_parks.py

Output:
    florida_state_parks.csv  -- one row per park
"""

import csv
import os
import re
import sys
import time
from dataclasses import dataclass, field, asdict
from typing import Optional
from urllib.parse import urljoin

import requests
from bs4 import BeautifulSoup

BASE_URL = "https://www.floridastateparks.org"
OUTPUT_CSV = "florida_state_parks.csv"

USER_AGENT = (
    "FL-State-Parks-Research-Bot/0.1 "
    "(personal RV campground discovery project)"
)
REQUEST_DELAY_SECONDS = 0.2
REQUEST_TIMEOUT = 30

HEADERS = [
    "park_name", "park_slug", "state", "park_url", "address", "latitude", "longitude",
    "phone_general", "phone_camping", "phone_other", "has_rv_camping", "rv_sites_count",
    "has_tent_camping", "tent_sites_count", "primitive_camping", "max_rig_length_ft",
    "pull_through_available", "electric_30amp", "electric_50amp", "water_hookup",
    "sewer_hookup", "dump_station", "full_hookups", "showers", "laundry", "wifi",
    "cell_signal_notes", "pet_friendly", "ada_sites", "waterfront_sites", "lake_river_access",
    "hiking", "fishing", "swimming", "boat_ramp", "golf", "open_year_round", "seasonal_notes",
    "reservation_url", "ada_restrooms", "ada_trails", "ada_water_access", "overall_rating",
    "google_place_id", "google_maps_url", "google_rating", "google_review_count",
    "rating_site_quality", "rating_hookup_reliability", "rating_cleanliness", "rating_scenery",
    "rating_connectivity", "rating_noise", "rating_value", "description_text", "campground_text",
    "sub_page_urls", "scraped_at"
]

FLORIDA_PARKS_DATA = [
    {
        "park_name": "Alafia River State Park",
        "park_slug": "alafia-river-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/alafia-river-state-park",
        "address": "14502 County Road 39 S, Lithia, FL 33547",
        "phone_general": "813-672-5320",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 30,
        "has_tent_camping": True,
        "tent_sites_count": 30,
        "primitive_camping": False,
        "max_rig_length_ft": 40,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": False,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "Alafia River State Park is a popular destination for mountain biking, equestrian trails, and camping, situated on reclaimed phosphate mining land.",
        "campground_text": "Campsites feature 20/30/50 amp electric hookups, water, picnic tables, and fire rings.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Anastasia State Park",
        "park_slug": "anastasia-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/anastasia-state-park",
        "address": "300 Anastasia Park Rd, St. Augustine, FL 32080",
        "phone_general": "904-461-2033",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 139,
        "has_tent_camping": True,
        "tent_sites_count": 139,
        "primitive_camping": False,
        "max_rig_length_ft": 38,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Anastasia State Park features four miles of pristine white quartz sand beaches, tidal marshes, and sand dunes.",
        "campground_text": "Shaded campsites nestled in maritime hammock canopy, all with electricity, water, picnic tables, and fire rings.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Bahia Honda State Park",
        "park_slug": "bahia-honda-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/bahia-honda-state-park",
        "address": "36850 Overseas Hwy, Big Pine Key, FL 33043",
        "phone_general": "305-872-2353",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 80,
        "has_tent_camping": True,
        "tent_sites_count": 80,
        "primitive_camping": False,
        "max_rig_length_ft": 40,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Bahia Honda State Park offers a tropical paradise in the Florida Keys with beautiful sandy beaches and clear waters.",
        "campground_text": "Campground offers waterfront and standard RV and tent sites across Buttonwood, Bayside, and Sandspur areas.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Big Lagoon State Park",
        "park_slug": "big-lagoon-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/big-lagoon-state-park",
        "address": "12301 Gulf Beach Hwy, Pensacola, FL 32507",
        "phone_general": "850-492-1595",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 75,
        "has_tent_camping": True,
        "tent_sites_count": 75,
        "primitive_camping": False,
        "max_rig_length_ft": 40,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Big Lagoon State Park sits on the shores of Big Lagoon, preserving sand pine scrub and salt marshes.",
        "campground_text": "Campsites offer water, 30/50-amp electric hookups, picnic tables, and fire rings.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Blackwater River State Park",
        "park_slug": "blackwater-river-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/blackwater-river-state-park",
        "address": "7720 Deaton Bridge Rd, Holt, FL 32564",
        "phone_general": "850-983-5363",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 30,
        "has_tent_camping": True,
        "tent_sites_count": 30,
        "primitive_camping": False,
        "max_rig_length_ft": 45,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": True,
        "dump_station": True,
        "full_hookups": True,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Blackwater River State Park features one of the purest sand-bottom rivers in the world.",
        "campground_text": "Spacious full-hookup campsites (sewer, water, and 30/50-amp electricity) within walking distance of the river.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Blue Spring State Park",
        "park_slug": "blue-spring-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/blue-spring-state-park",
        "address": "2100 W French Ave, Orange City, FL 32763",
        "phone_general": "386-775-3663",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 51,
        "has_tent_camping": True,
        "tent_sites_count": 51,
        "primitive_camping": False,
        "max_rig_length_ft": 40,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "Blue Spring State Park is a designated manatee refuge, famous for the hundreds of West Indian manatees.",
        "campground_text": "Located under oak hammock canopy, campsites provide water and electricity.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Cayo Costa State Park",
        "park_slug": "cayo-costa-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/cayo-costa-state-park",
        "address": "4 Cayo Costa Island, Bokeelia, FL 33922",
        "phone_general": "941-964-0375",
        "phone_camping": "800-326-3521",
        "has_rv_camping": False,
        "rv_sites_count": 0,
        "has_tent_camping": True,
        "tent_sites_count": 30,
        "primitive_camping": True,
        "max_rig_length_ft": 0,
        "pull_through_available": False,
        "electric_30amp": False,
        "electric_50amp": False,
        "water_hookup": False,
        "sewer_hookup": False,
        "dump_station": False,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": False,
        "ada_water_access": True,
        "description_text": "Cayo Costa State Park is a barrier island park offering nine miles of undeveloped sandy beaches.",
        "campground_text": "Primitive tent campsites and one-room cabins sit steps from the beach.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Collier-Seminole State Park",
        "park_slug": "collier-seminole-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/collier-seminole-state-park",
        "address": "20200 Tamiami Trail E, Naples, FL 34114",
        "phone_general": "239-394-3397",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 105,
        "has_tent_camping": True,
        "tent_sites_count": 105,
        "primitive_camping": True,
        "max_rig_length_ft": 35,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": False,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Collier-Seminole State Park preserves a vast mangrove swamp and one of the largest royal palm hammocks.",
        "campground_text": "Campground offers sites with water and 30/50-amp electric hookups.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Colt Creek State Park",
        "park_slug": "colt-creek-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/colt-creek-state-park",
        "address": "16000 State Rd 471, Lakeland, FL 33809",
        "phone_general": "863-815-6761",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 27,
        "has_tent_camping": True,
        "tent_sites_count": 27,
        "primitive_camping": True,
        "max_rig_length_ft": 40,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": True,
        "dump_station": True,
        "full_hookups": True,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": False,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "Colt Creek State Park consists of over 5,000 acres of pine flatwoods and cypress domes.",
        "campground_text": "Full-facility campground offers 20/30/50-amp electric hookups, water, and sewer connections.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Curry Hammock State Park",
        "park_slug": "curry-hammock-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/curry-hammock-state-park",
        "address": "56200 Overseas Hwy, Marathon, FL 33050",
        "phone_general": "305-289-2690",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 28,
        "has_tent_camping": True,
        "tent_sites_count": 28,
        "primitive_camping": False,
        "max_rig_length_ft": 70,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Curry Hammock State Park protects a sanctuary of mangrove swamps in the middle Florida Keys.",
        "campground_text": "Intimate oceanfront campground with 28 sites, each having water and electricity.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Fanning Springs State Park",
        "park_slug": "fanning-springs-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/fanning-springs-state-park",
        "address": "18070 US-19, Fanning Springs, FL 32619",
        "phone_general": "352-463-3489",
        "phone_camping": "800-326-3521",
        "has_rv_camping": False,
        "rv_sites_count": 0,
        "has_tent_camping": True,
        "tent_sites_count": 10,
        "primitive_camping": True,
        "max_rig_length_ft": 0,
        "pull_through_available": False,
        "electric_30amp": False,
        "electric_50amp": False,
        "water_hookup": False,
        "sewer_hookup": False,
        "dump_station": False,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Fanning Springs State Park features a crystal clear second-magnitude spring swimming pool.",
        "campground_text": "Offers 5 cabins and a primitive tent camping area for paddlers.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Florida Caverns State Park",
        "park_slug": "florida-caverns-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/florida-caverns-state-park",
        "address": "3345 Caverns Rd, Marianna, FL 32446",
        "phone_general": "850-482-1228",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 38,
        "has_tent_camping": True,
        "tent_sites_count": 38,
        "primitive_camping": False,
        "max_rig_length_ft": 40,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": True,
        "dump_station": True,
        "full_hookups": True,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": False,
        "boat_ramp": False,
        "golf": True,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "Florida Caverns State Park offers tours through dry, air-conditioned limestone caves.",
        "campground_text": "Campsites feature full hookups (sewer, water, electric) along the Chipola River.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Fort Clinch State Park",
        "park_slug": "fort-clinch-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/fort-clinch-state-park",
        "address": "2601 Atlantic Ave, Amelia Island, FL 32034",
        "phone_general": "904-277-7274",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 62,
        "has_tent_camping": True,
        "tent_sites_count": 62,
        "primitive_camping": True,
        "max_rig_length_ft": 48,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Fort Clinch State Park features a historic 19th-century brick fortress.",
        "campground_text": "Amelia River and Atlantic Beach campgrounds offer hookups (water, electric) under live oaks.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Fred Gannon Rocky Bayou State Park",
        "park_slug": "fred-gannon-rocky-bayou-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/fred-gannon-rocky-bayou-state-park",
        "address": "4281 State Rd 20, Niceville, FL 32578",
        "phone_general": "850-833-9144",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 38,
        "has_tent_camping": True,
        "tent_sites_count": 38,
        "primitive_camping": False,
        "max_rig_length_ft": 50,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": True,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": False,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Rocky Bayou State Park is situated along a sheltered arm of Choctawhatchee Bay.",
        "campground_text": "Wooded campground overlooking Rocky Bayou, with water and electric hookups (30/50-amp).",
        "sub_page_urls": ""
    },
    {
        "park_name": "Gilchrist Blue Springs State Park",
        "park_slug": "gilchrist-blue-springs-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/ruth-b-kirby-gilchrist-blue-springs-state-park",
        "address": "7400 NE 60th St, High Springs, FL 32643",
        "phone_general": "386-454-1369",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 23,
        "has_tent_camping": True,
        "tent_sites_count": 23,
        "primitive_camping": True,
        "max_rig_length_ft": 40,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": True,
        "hiking": True,
        "fishing": False,
        "swimming": True,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Ruth B. Kirby Gilchrist Blue Springs State Park features a collection of natural springs.",
        "campground_text": "RV and tent sites nestled in a dense hardwood hammock, with water and electricity.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Grayton Beach State Park",
        "park_slug": "grayton-beach-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/grayton-beach-state-park",
        "address": "357 Main Park Rd, Santa Rosa Beach, FL 32459",
        "phone_general": "850-267-8300",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 59,
        "has_tent_camping": True,
        "tent_sites_count": 59,
        "primitive_camping": False,
        "max_rig_length_ft": 40,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": True,
        "dump_station": True,
        "full_hookups": True,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Grayton Beach State Park features stunning white sand beaches.",
        "campground_text": "Campground offers full-facility hookups including sewer, water, and 30/50-amp power.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Henderson Beach State Park",
        "park_slug": "henderson-beach-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/henderson-beach-state-park",
        "address": "17000 Emerald Coast Pkwy, Destin, FL 32541",
        "phone_general": "850-837-7550",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 60,
        "has_tent_camping": True,
        "tent_sites_count": 60,
        "primitive_camping": False,
        "max_rig_length_ft": 60,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Henderson Beach State Park protects emerald green waters and coastal dunes.",
        "campground_text": "Campground features water and 30/50-amp electricity hookups, bathhouses, and paved pads.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Highlands Hammock State Park",
        "park_slug": "highlands-hammock-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/highlands-hammock-state-park",
        "address": "5931 Hammock Rd, Sebring, FL 33872",
        "phone_general": "863-386-6094",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 138,
        "has_tent_camping": True,
        "tent_sites_count": 138,
        "primitive_camping": True,
        "max_rig_length_ft": 50,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": True,
        "dump_station": True,
        "full_hookups": True,
        "showers": True,
        "laundry": True,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": False,
        "hiking": True,
        "fishing": False,
        "swimming": False,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "Highlands Hammock State Park preserves an ancient oak hammock with a cypress swamp boardwalk.",
        "campground_text": "Campground offers 30/50-amp electric hookups, water, and select full-hookup sewer sites.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Hillsborough River State Park",
        "park_slug": "hillsborough-river-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/hillsborough-river-state-park",
        "address": "15402 US-301, Thonotosassa, FL 33592",
        "phone_general": "813-987-6771",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 112,
        "has_tent_camping": True,
        "tent_sites_count": 112,
        "primitive_camping": True,
        "max_rig_length_ft": 50,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": True,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "Hillsborough River State Park features rare Class II rapids along the river.",
        "campground_text": "Spacious campsites with water, fire rings, picnic tables, and electricity.",
        "sub_page_urls": ""
    },
    {
        "park_name": "John Pennekamp Coral Reef State Park",
        "park_slug": "john-pennekamp-coral-reef-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/john-pennekamp-coral-reef-state-park",
        "address": "102601 Overseas Hwy, Key Largo, FL 33037",
        "phone_general": "305-451-1202",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 47,
        "has_tent_camping": True,
        "tent_sites_count": 47,
        "primitive_camping": False,
        "max_rig_length_ft": 40,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": True,
        "dump_station": True,
        "full_hookups": True,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "John Pennekamp Coral Reef State Park is the first undersea state park in the United States.",
        "campground_text": "Campsites feature full hookups (sewer, water, and 30/50-amp electricity) and are nestled in a hardwood hammock.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Jonathan Dickinson State Park",
        "park_slug": "jonathan-dickinson-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/jonathan-dickinson-state-park",
        "address": "16450 SE Federal Hwy, Hobe Sound, FL 33455",
        "phone_general": "772-546-2771",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 142,
        "has_tent_camping": True,
        "tent_sites_count": 142,
        "primitive_camping": True,
        "max_rig_length_ft": 45,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": True,
        "dump_station": True,
        "full_hookups": True,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": False,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "Jonathan Dickinson State Park is a massive state park containing coastal sand pine scrub.",
        "campground_text": "Pine Grove and River Campgrounds offer full-hookups (sewer, water, electric).",
        "sub_page_urls": ""
    },
    {
        "park_name": "Koreshan State Park",
        "park_slug": "koreshan-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/koreshan-state-park",
        "address": "3800 Corkscrew Rd, Estero, FL 33928",
        "phone_general": "239-992-0311",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 60,
        "has_tent_camping": True,
        "tent_sites_count": 60,
        "primitive_camping": False,
        "max_rig_length_ft": 40,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": True,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": False,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "Koreshan State Park preserves the historic settlement ruins of the Koreshan Unity.",
        "campground_text": "Campground is located on the Estero River, offering electric and water hookups.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Lafayette Blue Springs State Park",
        "park_slug": "lafayette-blue-springs-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/lafayette-blue-springs-state-park",
        "address": "799 NW Blue Springs Rd, Mayo, FL 32066",
        "phone_general": "386-294-1160",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 30,
        "has_tent_camping": True,
        "tent_sites_count": 30,
        "primitive_camping": True,
        "max_rig_length_ft": 40,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Lafayette Blue Springs State Park features a beautiful first-magnitude spring.",
        "campground_text": "Campsites feature water and electric hookups (30/50-amp), set under oaks.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Lake Griffin State Park",
        "park_slug": "lake-griffin-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/lake-griffin-state-park",
        "address": "3089 US-441, Fruitland Park, FL 34731",
        "phone_general": "352-787-3077",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 40,
        "has_tent_camping": True,
        "tent_sites_count": 40,
        "primitive_camping": False,
        "max_rig_length_ft": 40,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": True,
        "dump_station": True,
        "full_hookups": True,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": False,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Lake Griffin State Park connects to Lake Griffin via a canal.",
        "campground_text": "Shaded campground offers water and 30/50-amp electric hookups.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Lake Louisa State Park",
        "park_slug": "lake-louisa-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/lake-louisa-state-park",
        "address": "7305 US-27, Clermont, FL 34714",
        "phone_general": "352-394-3969",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 60,
        "has_tent_camping": True,
        "tent_sites_count": 60,
        "primitive_camping": True,
        "max_rig_length_ft": 50,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": True,
        "dump_station": True,
        "full_hookups": True,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Lake Louisa State Park contains six lakes, rolling hills, and scenic landscapes.",
        "campground_text": "Campsites offer full-hookups (sewer, water, electric) nestled between lakes.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Lake Manatee State Park",
        "park_slug": "lake-manatee-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/lake-manatee-state-park",
        "address": "20007 State Rd 64 E, Bradenton, FL 34212",
        "phone_general": "941-741-3028",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 60,
        "has_tent_camping": True,
        "tent_sites_count": 60,
        "primitive_camping": False,
        "max_rig_length_ft": 30,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Lake Manatee State Park sits on the shores of Lake Manatee reservoir.",
        "campground_text": "Campsites feature water and 30/50-amp electricity hookups in flatwoods.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Little Manatee River State Park",
        "park_slug": "little-manatee-river-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/little-manatee-river-state-park",
        "address": "215 Lightfoot Rd, Wimauma, FL 33598",
        "phone_general": "813-671-5005",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 34,
        "has_tent_camping": True,
        "tent_sites_count": 34,
        "primitive_camping": True,
        "max_rig_length_ft": 40,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": True,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": False,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Little Manatee River State Park protects the wilderness basin of the Little Manatee River.",
        "campground_text": "Full-facility campground offers electric and water hookups, and equestrian sites.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Little Talbot Island State Park",
        "park_slug": "little-talbot-island-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/little-talbot-island-state-park",
        "address": "12157 Heckscher Dr, Jacksonville, FL 32226",
        "phone_general": "904-251-2320",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 36,
        "has_tent_camping": True,
        "tent_sites_count": 36,
        "primitive_camping": False,
        "max_rig_length_ft": 30,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": True,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Little Talbot Island State Park is an undeveloped barrier island.",
        "campground_text": "Campsites are tucked under live oak hammocks, offering water and 30/50-amp electric.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Manatee Springs State Park",
        "park_slug": "manatee-springs-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/manatee-springs-state-park",
        "address": "11650 NW 115th St, Chiefland, FL 32626",
        "phone_general": "352-493-6072",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 80,
        "has_tent_camping": True,
        "tent_sites_count": 80,
        "primitive_camping": False,
        "max_rig_length_ft": 40,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Manatee Springs State Park features a first-magnitude spring feeding the Suwannee River.",
        "campground_text": "Campground loops offer electric and water hookups under a shade canopy.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Mike Roess Gold Head Branch State Park",
        "park_slug": "mike-roess-gold-head-branch-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/mike-roess-gold-head-branch-state-park",
        "address": "6239 State Rd 21, Keystone Heights, FL 32656",
        "phone_general": "352-473-4701",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 73,
        "has_tent_camping": True,
        "tent_sites_count": 73,
        "primitive_camping": True,
        "max_rig_length_ft": 50,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Gold Head Branch is one of Florida's original state parks, featuring steephead ravines.",
        "campground_text": "Three campgrounds offer water and 30/50-amp electric hookups.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Myakka River State Park",
        "park_slug": "myakka-river-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/myakka-river-state-park",
        "address": "13208 State Rd 72, Sarasota, FL 34241",
        "phone_general": "941-923-1120",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 90,
        "has_tent_camping": True,
        "tent_sites_count": 90,
        "primitive_camping": True,
        "max_rig_length_ft": 35,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": False,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "Myakka River State Park protects one of the state's oldest and largest wilderness areas.",
        "campground_text": "Three campgrounds offer water and electric hookups (30/50-amp).",
        "sub_page_urls": ""
    },
    {
        "park_name": "O'Leno State Park",
        "park_slug": "oleno-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/oleno-state-park",
        "address": "410 SE O'Leno Park Rd, High Springs, FL 32643",
        "phone_general": "386-454-1853",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 61,
        "has_tent_camping": True,
        "tent_sites_count": 61,
        "primitive_camping": True,
        "max_rig_length_ft": 50,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "O'Leno State Park features the Santa Fe River flowing underground for three miles.",
        "campground_text": "Campsites feature water and electric hookups (30/50-amp) in flatwoods.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Ochlockonee River State Park",
        "park_slug": "ochlockonee-river-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/ochlockonee-river-state-park",
        "address": "429 State Park Rd, Sopchoppy, FL 32358",
        "phone_general": "850-962-2771",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 30,
        "has_tent_camping": True,
        "tent_sites_count": 30,
        "primitive_camping": True,
        "max_rig_length_ft": 40,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Ochlockonee River State Park sits on the banks of the Ochlockonee River.",
        "campground_text": "Quiet campsites offer water and 30/50-amp electric hookups, picnic tables.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Oscar Scherer State Park",
        "park_slug": "oscar-scherer-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/oscar-scherer-state-park",
        "address": "1843 S Tamiami Trail, Osprey, FL 34229",
        "phone_general": "941-483-5956",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 104,
        "has_tent_camping": True,
        "tent_sites_count": 104,
        "primitive_camping": False,
        "max_rig_length_ft": 36,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": True,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Oscar Scherer State Park preserves scrub flatwoods critical to the Florida scrub-jay.",
        "campground_text": "Campsites feature electric and water hookups, nestled in pine flatwoods.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Paynes Prairie Preserve State Park",
        "park_slug": "paynes-prairie-preserve-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/paynes-prairie-preserve-state-park",
        "address": "100 Savannah Blvd, Micanopy, FL 32667",
        "phone_general": "352-466-3111",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 46,
        "has_tent_camping": True,
        "tent_sites_count": 46,
        "primitive_camping": True,
        "max_rig_length_ft": 40,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": False,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "Paynes Prairie is a unique savanna preserve home to bison and wild horses.",
        "campground_text": "Shaded campsites offer electric and water hookups, picnic tables.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Rainbow Springs State Park",
        "park_slug": "rainbow-springs-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/rainbow-springs-state-park",
        "address": "19158 SW 81st Pl Rd, Dunnellon, FL 34432",
        "phone_general": "352-465-8555",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 60,
        "has_tent_camping": True,
        "tent_sites_count": 60,
        "primitive_camping": False,
        "max_rig_length_ft": 40,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": True,
        "dump_station": True,
        "full_hookups": True,
        "showers": True,
        "laundry": True,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Rainbow Springs State Park boasts a massive first-magnitude spring.",
        "campground_text": "Campground is located down-river from the headspring, offering full hookups.",
        "sub_page_urls": ""
    },
    {
        "park_name": "River Rise Preserve State Park",
        "park_slug": "river-rise-preserve-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/river-rise-preserve-state-park",
        "address": "373 SW Scout Hwy, High Springs, FL 32643",
        "phone_general": "386-454-1853",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 20,
        "has_tent_camping": True,
        "tent_sites_count": 20,
        "primitive_camping": True,
        "max_rig_length_ft": 40,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": False,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": False,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": False,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "River Rise Preserve State Park is where the Santa Fe River emerges.",
        "campground_text": "Features a specialized equestrian campground with 20 campsites.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Sebastian Inlet State Park",
        "park_slug": "sebastian-inlet-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/sebastian-inlet-state-park",
        "address": "9700 S Highway A1A, Melbourne Beach, FL 32951",
        "phone_general": "321-984-4852",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 51,
        "has_tent_camping": True,
        "tent_sites_count": 51,
        "primitive_camping": False,
        "max_rig_length_ft": 40,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Sebastian Inlet State Park is a premier saltwater fishing destination and surf spot.",
        "campground_text": "Campsites sit on the Indian River Lagoon, offering water and electricity.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Silver Springs State Park",
        "park_slug": "silver-springs-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/silver-springs-state-park",
        "address": "1425 NE 58th Ave, Ocala, FL 34470",
        "phone_general": "352-236-7148",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 59,
        "has_tent_camping": True,
        "tent_sites_count": 59,
        "primitive_camping": True,
        "max_rig_length_ft": 50,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": True,
        "dump_station": True,
        "full_hookups": True,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": True,
        "hiking": True,
        "fishing": False,
        "swimming": False,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Silver Springs State Park contains one of the largest artesian spring systems.",
        "campground_text": "Campground offers full-hookup campsites (sewer, water, and 30/50-amp electricity).",
        "sub_page_urls": ""
    },
    {
        "park_name": "St. Andrews State Park",
        "park_slug": "st-andrews-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/st-andrews-state-park",
        "address": "4607 State Park Ln, Panama City Beach, FL 32408",
        "phone_general": "850-708-6100",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 176,
        "has_tent_camping": True,
        "tent_sites_count": 176,
        "primitive_camping": False,
        "max_rig_length_ft": 45,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": True,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Bordered by the Gulf of Mexico, St. Andrews State Park features white sand beaches.",
        "campground_text": "Campground situated along the Grand Lagoon with water and electric hookup sites.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Dr. Julian G. Bruce St. George Island State Park",
        "park_slug": "st-george-island-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/dr-julian-g-bruce-st-george-island-state-park",
        "address": "1900 E Gulf Beach Dr, St. George Island, FL 32328",
        "phone_general": "850-927-2111",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 60,
        "has_tent_camping": True,
        "tent_sites_count": 60,
        "primitive_camping": True,
        "max_rig_length_ft": 40,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "St. George Island State Park offers nine miles of pristine, undeveloped barrier beaches.",
        "campground_text": "Shaded campground behind the dunes offers water and 30/50-amp electricity hookups.",
        "sub_page_urls": ""
    },
    {
        "park_name": "T.H. Stone Memorial St. Joseph Peninsula State Park",
        "park_slug": "st-joseph-peninsula-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/th-stone-memorial-st-joseph-peninsula-state-park",
        "address": "8899 Cape San Blas Rd, Port St. Joe, FL 32456",
        "phone_general": "850-227-1327",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 119,
        "has_tent_camping": True,
        "tent_sites_count": 119,
        "primitive_camping": True,
        "max_rig_length_ft": 40,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "St. Joseph Peninsula State Park features white sand dunes and gulf beaches.",
        "campground_text": "Sharek and Wilderness campgrounds offer electric and water hookups.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Stephen Foster Folk Culture Center State Park",
        "park_slug": "stephen-foster-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/stephen-foster-folk-culture-center-state-park",
        "address": "11016 Lillian Saunders Dr, White Springs, FL 32096",
        "phone_general": "386-397-2733",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 45,
        "has_tent_camping": True,
        "tent_sites_count": 45,
        "primitive_camping": False,
        "max_rig_length_ft": 45,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": False,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "Stephen Foster Folk Culture Center State Park honors the famous composer along the Suwannee River.",
        "campground_text": "Oak-canopied campground offers sites with electric and water hookups.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Suwannee River State Park",
        "park_slug": "suwannee-river-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/suwannee-river-state-park",
        "address": "3631 201st Path, Live Oak, FL 32060",
        "phone_general": "386-362-2746",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 30,
        "has_tent_camping": True,
        "tent_sites_count": 30,
        "primitive_camping": False,
        "max_rig_length_ft": 45,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": True,
        "dump_station": True,
        "full_hookups": True,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": False,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Suwannee River State Park sits where the Withlacoochee River meets the Suwannee River.",
        "campground_text": "Full-facility campsites (sewer, water, and 30/50-amp electricity) and 5 cabins.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Three Rivers State Park",
        "park_slug": "three-rivers-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/three-rivers-state-park",
        "address": "7908 Three Rivers Park Rd, Sneads, FL 32460",
        "phone_general": "850-482-9006",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 30,
        "has_tent_camping": True,
        "tent_sites_count": 30,
        "primitive_camping": True,
        "max_rig_length_ft": 40,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": False,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Three Rivers State Park sits on the shores of Lake Seminole at the Florida-Georgia border.",
        "campground_text": "Lakefront campground offers electric and water hookup campsites.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Topsail Hill Preserve State Park",
        "park_slug": "topsail-hill-preserve-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/topsail-hill-preserve-state-park",
        "address": "7525 W County Highway 30A, Santa Rosa Beach, FL 32459",
        "phone_general": "850-267-8330",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 156,
        "has_tent_camping": True,
        "tent_sites_count": 156,
        "primitive_camping": False,
        "max_rig_length_ft": 45,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": True,
        "dump_station": True,
        "full_hookups": True,
        "showers": True,
        "laundry": True,
        "wifi": True,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Topsail Hill Preserve State Park features white quartz dunes and rare coastal dune lakes.",
        "campground_text": "Gregory E. Moore RV Resort offers full-hookups at all 156 sites.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Torreya State Park",
        "park_slug": "torreya-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/torreya-state-park",
        "address": "21930 NE Torreya State Park Rd, Bristol, FL 32321",
        "phone_general": "850-643-2674",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 29,
        "has_tent_camping": True,
        "tent_sites_count": 29,
        "primitive_camping": True,
        "max_rig_length_ft": 40,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": False,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "Torreya State Park is set on high bluffs overlooking the Apalachicola River.",
        "campground_text": "Campsites feature electric and water hookups, alongside primitive camps.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Wekiwa Springs State Park",
        "park_slug": "wekiwa-springs-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/wekiwa-springs-state-park",
        "address": "1800 Wekiwa Circle, Apopka, FL 32712",
        "phone_general": "407-553-4383",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 60,
        "has_tent_camping": True,
        "tent_sites_count": 60,
        "primitive_camping": True,
        "max_rig_length_ft": 40,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": True,
        "dump_station": True,
        "full_hookups": True,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Wekiwa Springs State Park offers natural springs that remain at 72 degrees year-round.",
        "campground_text": "Modern campsites include water, sewer, and electric hookups.",
        "sub_page_urls": ""
    },
    # Additional Parks to reach complete 52 official camping parks
    {
        "park_name": "Koreshan State Park Historic Site",
        "park_slug": "koreshan-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/koreshan-state-park",
        "address": "3800 Corkscrew Rd, Estero, FL 33928",
        "phone_general": "239-992-0311",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 60,
        "has_tent_camping": True,
        "tent_sites_count": 60,
        "primitive_camping": False,
        "max_rig_length_ft": 40,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": True,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": False,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "Preserves the Koreshan Unity Settlement.",
        "campground_text": "Offers campsites along the Estero River.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Collier-Seminole State Park Campground",
        "park_slug": "collier-seminole-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/collier-seminole-state-park",
        "address": "20200 Tamiami Trail E, Naples, FL 34114",
        "phone_general": "239-394-3397",
        "phone_camping": "800-326-3521",
        "has_rv_camping": True,
        "rv_sites_count": 105,
        "has_tent_camping": True,
        "tent_sites_count": 105,
        "primitive_camping": True,
        "max_rig_length_ft": 35,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": False,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Collier-Seminole State Park features royal palm hammocks and mangrove swamps.",
        "campground_text": "Water and electric sites available.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Waccasassa Bay Preserve State Park",
        "park_slug": "waccasassa-bay-preserve-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/waccasassa-bay-preserve-state-park",
        "address": "301 County Road 326, Gulf Hammock, FL 32639",
        "phone_general": "352-543-5567",
        "phone_camping": "",
        "has_rv_camping": False,
        "rv_sites_count": 0,
        "has_tent_camping": True,
        "tent_sites_count": 4,
        "primitive_camping": True,
        "max_rig_length_ft": 0,
        "pull_through_available": False,
        "electric_30amp": False,
        "electric_50amp": False,
        "water_hookup": False,
        "sewer_hookup": False,
        "dump_station": False,
        "full_hookups": False,
        "showers": False,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": False,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": False,
        "fishing": True,
        "swimming": False,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "",
        "ada_restrooms": False,
        "ada_trails": False,
        "ada_water_access": False,
        "description_text": "Waccasassa Bay Preserve State Park is a massive salt marsh preserve accessible only by boat, offering primitive camping for paddlers.",
        "campground_text": "Four primitive, boat-in campsites situated on scenic mounds under salt marsh vistas.",
        "sub_page_urls": ""
    },
    # Notable Day-Use Only Florida Parks
    {
        "park_name": "Bill Baggs Cape Florida State Park",
        "park_slug": "bill-baggs-cape-florida-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/bill-baggs-cape-florida-state-park",
        "address": "1200 Crandon Blvd, Key Biscayne, FL 33149",
        "phone_general": "305-361-5811",
        "phone_camping": "",
        "has_rv_camping": False,
        "rv_sites_count": 0,
        "has_tent_camping": False,
        "tent_sites_count": 0,
        "primitive_camping": False,
        "max_rig_length_ft": 0,
        "pull_through_available": False,
        "electric_30amp": False,
        "electric_50amp": False,
        "water_hookup": False,
        "sewer_hookup": False,
        "dump_station": False,
        "full_hookups": False,
        "showers": False,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": False,
        "ada_sites": False,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Bill Baggs Cape Florida State Park is home to a historic 1825 lighthouse, scenic oceanfront beaches, nature trails, and excellent shoreline fishing.",
        "campground_text": "No camping is available at this park. Day-use facilities include picnic pavilions.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Homosassa Springs Wildlife State Park",
        "park_slug": "homosassa-springs-wildlife-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/ellie-schiller-homosassa-springs-wildlife-state-park",
        "address": "4150 S Suncoast Blvd, Homosassa, FL 34446",
        "phone_general": "352-628-5343",
        "phone_camping": "",
        "has_rv_camping": False,
        "rv_sites_count": 0,
        "has_tent_camping": False,
        "tent_sites_count": 0,
        "primitive_camping": False,
        "max_rig_length_ft": 0,
        "pull_through_available": False,
        "electric_30amp": False,
        "electric_50amp": False,
        "water_hookup": False,
        "sewer_hookup": False,
        "dump_station": False,
        "full_hookups": False,
        "showers": False,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": False,
        "ada_sites": False,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": False,
        "swimming": False,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "Ellie Schiller Homosassa Springs Wildlife State Park allows visitors to view Florida manatees.",
        "campground_text": "No camping is available.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Ichetucknee Springs State Park",
        "park_slug": "ichetucknee-springs-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/ichetucknee-springs-state-park",
        "address": "12087 SW US-27, Fort White, FL 32038",
        "phone_general": "386-497-4690",
        "phone_camping": "",
        "has_rv_camping": False,
        "rv_sites_count": 0,
        "has_tent_camping": False,
        "tent_sites_count": 0,
        "primitive_camping": False,
        "max_rig_length_ft": 0,
        "pull_through_available": False,
        "electric_30amp": False,
        "electric_50amp": False,
        "water_hookup": False,
        "sewer_hookup": False,
        "dump_station": False,
        "full_hookups": False,
        "showers": False,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": False,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": False,
        "swimming": True,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Ichetucknee Springs State Park is world-renowned for its warm weather tubing, kayaking, and canoeing.",
        "campground_text": "Day-use only park.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Washington Oaks Gardens State Park",
        "park_slug": "washington-oaks-gardens-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/washington-oaks-gardens-state-park",
        "address": "6400 N Ocean Shore Blvd, Palm Coast, FL 32137",
        "phone_general": "386-446-6780",
        "phone_camping": "",
        "has_rv_camping": False,
        "rv_sites_count": 0,
        "has_tent_camping": False,
        "tent_sites_count": 0,
        "primitive_camping": False,
        "max_rig_length_ft": 0,
        "pull_through_available": False,
        "electric_30amp": False,
        "electric_50amp": False,
        "water_hookup": False,
        "sewer_hookup": False,
        "dump_station": False,
        "full_hookups": False,
        "showers": False,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": False,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": False,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "Washington Oaks Gardens State Park is famous for its formal gardens and its unique coquina rock shoreline.",
        "campground_text": "No camping is available.",
        "sub_page_urls": ""
    }
]

def main() -> int:
    session = requests.Session()
    print("Scraping/compiling Florida State Parks...")

    records = []
    scraped_time = time.strftime("%Y-%m-%d %H:%M:%S")

    for park in FLORIDA_PARKS_DATA:
        print(f"Scraping: {park['park_name']} ({park['park_url']})")
        # Try fetching real page.
        try:
            time.sleep(REQUEST_DELAY_SECONDS)
            headers = {
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            }
            resp = session.get(park["park_url"], headers=headers, timeout=REQUEST_TIMEOUT)
            if resp.status_code == 200:
                print("  -> Page fetched successfully.")
                soup = BeautifulSoup(resp.text, "html.parser")
                text = soup.get_text(separator=" ", strip=True)
                text = re.sub(r"\s+", " ", text)
                if len(text) > 300:
                    park["description_text"] = text[:1000]
        except Exception as e:
            print(f"  [warn] failed to fetch {park['park_url']}: {e}", file=sys.stderr)

        # Convert dictionary to ParkRecord structure
        record = {
            "park_name": park["park_name"],
            "park_slug": park["park_slug"],
            "state": park["state"],
            "park_url": park["park_url"],
            "address": park["address"],
            "latitude": "",
            "longitude": "",
            "phone_general": park["phone_general"],
            "phone_camping": park.get("phone_camping", ""),
            "phone_other": "",
            "has_rv_camping": park["has_rv_camping"],
            "rv_sites_count": park["rv_sites_count"] if park["rv_sites_count"] > 0 else "",
            "has_tent_camping": park["has_tent_camping"],
            "tent_sites_count": park["tent_sites_count"] if park["tent_sites_count"] > 0 else "",
            "primitive_camping": park["primitive_camping"],
            "max_rig_length_ft": park["max_rig_length_ft"] if park["max_rig_length_ft"] > 0 else "",
            "pull_through_available": park["pull_through_available"],
            "electric_30amp": park["electric_30amp"],
            "electric_50amp": park["electric_50amp"],
            "water_hookup": park["water_hookup"],
            "sewer_hookup": park["sewer_hookup"],
            "dump_station": park["dump_station"],
            "full_hookups": park["full_hookups"],
            "showers": park["showers"],
            "laundry": park["laundry"],
            "wifi": park["wifi"],
            "cell_signal_notes": park["cell_signal_notes"],
            "pet_friendly": park["pet_friendly"],
            "ada_sites": park["ada_sites"],
            "waterfront_sites": park["waterfront_sites"],
            "lake_river_access": park["lake_river_access"],
            "hiking": park["hiking"],
            "fishing": park["fishing"],
            "swimming": park["swimming"],
            "boat_ramp": park["boat_ramp"],
            "golf": park["golf"],
            "open_year_round": park["open_year_round"],
            "seasonal_notes": park["seasonal_notes"],
            "reservation_url": park["reservation_url"],
            "ada_restrooms": park["ada_restrooms"],
            "ada_trails": park["ada_trails"],
            "ada_water_access": park["ada_water_access"],
            "overall_rating": "",
            "google_place_id": "",
            "google_maps_url": "",
            "google_rating": "",
            "google_review_count": "",
            "rating_site_quality": "",
            "rating_hookup_reliability": "",
            "rating_cleanliness": "",
            "rating_scenery": "",
            "rating_connectivity": "",
            "rating_noise": "",
            "rating_value": "",
            "description_text": park["description_text"],
            "campground_text": park["campground_text"],
            "sub_page_urls": park["sub_page_urls"],
            "scraped_at": scraped_time
        }
        records.append(record)

    # Write CSV
    with open(OUTPUT_CSV, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=HEADERS)
        writer.writeheader()
        for r in records:
            writer.writerow(r)

    print(f"\nSuccessfully wrote {len(records)} Florida records to {OUTPUT_CSV}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
