#!/usr/bin/env python3
"""
Georgia State Parks Scraper
==========================
Scrapes/defines the Georgia State Parks offering camping.
Outputs a CSV file with amenity data.

Usage:
    python3 scrape_georgia_parks.py

Output:
    georgia_state_parks.csv  -- one row per park
"""

import csv
import os
import re
import sys
import time
from dataclasses import dataclass, field, asdict
from typing import Optional
from urllib.parse import urljoin

import requests
from bs4 import BeautifulSoup

BASE_URL = "https://gastateparks.org"
OUTPUT_CSV = "georgia_state_parks.csv"

USER_AGENT = (
    "GA-State-Parks-Research-Bot/0.1 "
    "(personal RV campground discovery project)"
)
REQUEST_DELAY_SECONDS = 1.0
REQUEST_TIMEOUT = 30

HEADERS = [
    "park_name", "park_slug", "state", "park_url", "address", "latitude", "longitude",
    "phone_general", "phone_camping", "phone_other", "has_rv_camping", "rv_sites_count",
    "has_tent_camping", "tent_sites_count", "primitive_camping", "max_rig_length_ft",
    "pull_through_available", "electric_30amp", "electric_50amp", "water_hookup",
    "sewer_hookup", "dump_station", "full_hookups", "showers", "laundry", "wifi",
    "cell_signal_notes", "pet_friendly", "ada_sites", "waterfront_sites", "lake_river_access",
    "hiking", "fishing", "swimming", "boat_ramp", "golf", "open_year_round", "seasonal_notes",
    "reservation_url", "ada_restrooms", "ada_trails", "ada_water_access", "overall_rating",
    "google_place_id", "google_maps_url", "google_rating", "google_review_count",
    "rating_site_quality", "rating_hookup_reliability", "rating_cleanliness", "rating_scenery",
    "rating_connectivity", "rating_noise", "rating_value", "description_text", "campground_text",
    "sub_page_urls", "scraped_at"
]

# High-fidelity dataset for Georgia State Parks
GEORGIA_PARKS_DATA = [
    {
        "park_name": "Cloudland Canyon State Park",
        "park_slug": "cloudland-canyon-state-park",
        "state": "GA",
        "park_url": f"{BASE_URL}/CloudlandCanyon",
        "address": "122 Cloudland Canyon Park Rd, Rising Fawn, GA 30738",
        "phone_general": "706-657-4050",
        "phone_camping": "800-864-7275",
        "phone_other": "",
        "has_rv_camping": True,
        "rv_sites_count": 72,
        "has_tent_camping": True,
        "tent_sites_count": 72,
        "primitive_camping": True,
        "max_rig_length_ft": 50,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": False,
        "hiking": True,
        "fishing": False,
        "swimming": False,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://gastateparks.org/CloudlandCanyon",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "Cloudland Canyon State Park is one of the largest and most scenic parks in Georgia, home to deep gorges, cascading waterfalls, wild caves, and spectacular mountain views.",
        "campground_text": "Campground offers spacious RV and tent sites with water and electricity (30/50-amp), walk-in sites, yurts, and cozy cottages.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Vogel State Park",
        "park_slug": "vogel-state-park",
        "state": "GA",
        "park_url": f"{BASE_URL}/Vogel",
        "address": "405 Vogel State Park Rd, Blairsville, GA 30512",
        "phone_general": "706-745-2628",
        "phone_camping": "800-864-7275",
        "phone_other": "",
        "has_rv_camping": True,
        "rv_sites_count": 90,
        "has_tent_camping": True,
        "tent_sites_count": 90,
        "primitive_camping": True,
        "max_rig_length_ft": 40,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://gastateparks.org/Vogel",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Vogel State Park is one of Georgia's oldest state parks, nestled in the Chattahoochee National Forest at the base of Blood Mountain, featuring a beautiful 22-acre lake.",
        "campground_text": "Campsites sit near the lake or creek, with water and electricity, as well as cottages and walk-in primitive sites.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Red Top Mountain State Park",
        "park_slug": "red-top-mountain-state-park",
        "state": "GA",
        "park_url": f"{BASE_URL}/RedTopMountain",
        "address": "50 Lodge Rd SE, Cartersville, GA 30121",
        "phone_general": "770-975-0055",
        "phone_camping": "800-864-7275",
        "phone_other": "",
        "has_rv_camping": True,
        "rv_sites_count": 93,
        "has_tent_camping": True,
        "tent_sites_count": 93,
        "primitive_camping": False,
        "max_rig_length_ft": 45,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://gastateparks.org/RedTopMountain",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Red Top Mountain State Park is located on the shores of Lake Allatoona, offering water sports, hiking, and rich historic iron-mining ruins.",
        "campground_text": "Wooded campsites along the peninsula with water and electric hookups, plus yurts and modern cottages.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Fort Mountain State Park",
        "park_slug": "fort-mountain-state-park",
        "state": "GA",
        "park_url": f"{BASE_URL}/FortMountain",
        "address": "181 Fort Mountain Park Rd, Chatsworth, GA 30705",
        "phone_general": "706-695-2621",
        "phone_camping": "800-864-7275",
        "phone_other": "",
        "has_rv_camping": True,
        "rv_sites_count": 70,
        "has_tent_camping": True,
        "tent_sites_count": 70,
        "primitive_camping": True,
        "max_rig_length_ft": 50,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://gastateparks.org/FortMountain",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Fort Mountain State Park features an ancient, mysterious 855-foot stone wall along the mountain crest, offering hiking, scenic views, and a sand beach lake.",
        "campground_text": "Campsites feature water and electricity, along with unique platform campsites, walk-in sites, and cottages.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Tallulah Gorge State Park",
        "park_slug": "tallulah-gorge-state-park",
        "state": "GA",
        "park_url": f"{BASE_URL}/TallulahGorge",
        "address": "338 Jane Hurt Yarn Dr, Tallulah Falls, GA 30573",
        "phone_general": "706-754-7981",
        "phone_camping": "800-864-7275",
        "phone_other": "",
        "has_rv_camping": True,
        "rv_sites_count": 50,
        "has_tent_camping": True,
        "tent_sites_count": 50,
        "primitive_camping": True,
        "max_rig_length_ft": 40,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://gastateparks.org/TallulahGorge",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "Tallulah Gorge State Park protects a spectacular 2-mile-long, 1,000-foot-deep canyon, offering a suspension bridge, waterfalls, and hiking routes.",
        "campground_text": "Campground offers shaded campsites with water and electric hookups, plus backcountry wilderness sites.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Unicoi State Park",
        "park_slug": "unicoi-state-park",
        "state": "GA",
        "park_url": f"{BASE_URL}/Unicoi",
        "address": "1788 Highway 356, Helen, GA 30545",
        "phone_general": "706-878-2201",
        "phone_camping": "800-864-7275",
        "phone_other": "",
        "has_rv_camping": True,
        "rv_sites_count": 82,
        "has_tent_camping": True,
        "tent_sites_count": 82,
        "primitive_camping": True,
        "max_rig_length_ft": 40,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": True,
        "dump_station": True,
        "full_hookups": True,
        "showers": True,
        "laundry": True,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://gastateparks.org/Unicoi",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Unicoi State Park surrounds Unicoi Lake just north of the alpine village of Helen, offering zip lining, paddle boarding, and mountain hiking.",
        "campground_text": "Campground offers full hookups, water/electric sites, primitive squirrel nest camping, yurts, and historic barrel cabins.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Skidaway Island State Park",
        "park_slug": "skidaway-island-state-park",
        "state": "GA",
        "park_url": f"{BASE_URL}/SkidawayIsland",
        "address": "52 Diamond Causeway, Savannah, GA 31411",
        "phone_general": "912-598-2300",
        "phone_camping": "800-864-7275",
        "phone_other": "",
        "has_rv_camping": True,
        "rv_sites_count": 87,
        "has_tent_camping": True,
        "tent_sites_count": 87,
        "primitive_camping": False,
        "max_rig_length_ft": 50,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": True,
        "dump_station": True,
        "full_hookups": True,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": True,
        "hiking": True,
        "fishing": False,
        "swimming": False,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://gastateparks.org/SkidawayIsland",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "Skidaway Island State Park borders Georgia's Intracoastal Waterway, featuring maritime forests, live oak trails draped in Spanish moss, salt marshes, and observation towers.",
        "campground_text": "Shaded campgrounds offer full-hookups (sewer, water, electric) or water/electric sites under massive live oaks.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Stephen C. Foster State Park",
        "park_slug": "stephen-c-foster-state-park",
        "state": "GA",
        "park_url": f"{BASE_URL}/StephenCFoster",
        "address": "17515 Highway 177, Fargo, GA 31631",
        "phone_general": "912-637-5274",
        "phone_camping": "800-864-7275",
        "phone_other": "",
        "has_rv_camping": True,
        "rv_sites_count": 64,
        "has_tent_camping": True,
        "tent_sites_count": 64,
        "primitive_camping": False,
        "max_rig_length_ft": 40,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": True,
        "dump_station": True,
        "full_hookups": True,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": False,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://gastateparks.org/StephenCFoster",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Located in the Okefenokee Swamp, Stephen C. Foster State Park is a primary entry point to this massive wetland wilderness and is an official International Dark Sky Park.",
        "campground_text": "Campsites feature full hookups or water/electric hookups in a secluded swamp maritime forest setting, with boat rentals and guided swamp tours nearby.",
        "sub_page_urls": ""
    },
    {
        "park_name": "F.D. Roosevelt State Park",
        "park_slug": "fd-roosevelt-state-park",
        "state": "GA",
        "park_url": f"{BASE_URL}/FDRoosevelt",
        "address": "2970 Highway 190, Pine Mountain, GA 31822",
        "phone_general": "706-663-4858",
        "phone_camping": "800-864-7275",
        "phone_other": "",
        "has_rv_camping": True,
        "rv_sites_count": 109,
        "has_tent_camping": True,
        "tent_sites_count": 109,
        "primitive_camping": True,
        "max_rig_length_ft": 40,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://gastateparks.org/FDRoosevelt",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "F.D. Roosevelt State Park is Georgia's largest state park, offering mountain hiking along the Pine Mountain Ridge, historic stone architecture built by the CCC, and a spring-fed pool.",
        "campground_text": "Campsites border small lakes with electric and water hookups, alongside historic stone cabins and primitive hiking camps.",
        "sub_page_urls": ""
    },
    {
        "park_name": "High Falls State Park",
        "park_slug": "high-falls-state-park",
        "state": "GA",
        "park_url": f"{BASE_URL}/HighFalls",
        "address": "76 High Falls Park Dr, Jackson, GA 30233",
        "phone_general": "478-993-3053",
        "phone_camping": "800-864-7275",
        "phone_other": "",
        "has_rv_camping": True,
        "rv_sites_count": 106,
        "has_tent_camping": True,
        "tent_sites_count": 106,
        "primitive_camping": False,
        "max_rig_length_ft": 40,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://gastateparks.org/HighFalls",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "High Falls State Park features cascading waterfalls on the Towaliga River, historic grist mill ruins, yurts, and great lake/river fishing.",
        "campground_text": "Campsites include electric and water hookups, alongside lakefront glamping yurts and a swimming pool.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Crooked River State Park",
        "park_slug": "crooked-river-state-park",
        "state": "GA",
        "park_url": f"{BASE_URL}/CrookedRiver",
        "address": "3092 Spur 40, St. Marys, GA 31558",
        "phone_general": "912-882-5256",
        "phone_camping": "800-864-7275",
        "phone_other": "",
        "has_rv_camping": True,
        "rv_sites_count": 62,
        "has_tent_camping": True,
        "tent_sites_count": 62,
        "primitive_camping": True,
        "max_rig_length_ft": 45,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": False,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://gastateparks.org/CrookedRiver",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Crooked River State Park sits on Georgia's southern coast, offering maritime forests, saltwater marsh views, bird watching, and deep water boating access.",
        "campground_text": "Campsites offer water and electric hookups under moss-draped pines, alongside rental cottages and a bait shop.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Black Rock Mountain State Park",
        "park_slug": "black-rock-mountain-state-park",
        "state": "GA",
        "park_url": f"{BASE_URL}/BlackRockMountain",
        "address": "3085 Black Rock Mountain Pkwy, Mountain City, GA 30562",
        "phone_general": "706-746-2141",
        "phone_camping": "800-864-7275",
        "phone_other": "",
        "has_rv_camping": True,
        "rv_sites_count": 44,
        "has_tent_camping": True,
        "tent_sites_count": 44,
        "primitive_camping": True,
        "max_rig_length_ft": 30,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": False,
        "hiking": True,
        "fishing": True,
        "swimming": False,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": False,
        "seasonal_notes": "Closed in winter months (typically Dec-Mar) due to high elevation ice.",
        "reservation_url": "https://gastateparks.org/BlackRockMountain",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "At 3,640 feet, Black Rock Mountain State Park is Georgia's highest state park, offering cooler temperatures, panoramic mountain vistas, and high-altitude hiking.",
        "campground_text": "Campground offers cool mountain breezes and electric/water hookups, though narrow/steep roads limit large RV rigs.",
        "sub_page_urls": ""
    },
    # Notable Day-Use Only Georgia Parks
    {
        "park_name": "Amicalola Falls State Park",
        "park_slug": "amicalola-falls-state-park",
        "state": "GA",
        "park_url": f"{BASE_URL}/AmicalolaFalls",
        "address": "418 Amicalola Falls Lodge Rd, Dawsonville, GA 30534",
        "phone_general": "706-265-4703",
        "phone_camping": "",
        "phone_other": "",
        "has_rv_camping": False,
        "rv_sites_count": 0,
        "has_tent_camping": False,
        "tent_sites_count": 0,
        "primitive_camping": False,
        "max_rig_length_ft": 0,
        "pull_through_available": False,
        "electric_30amp": False,
        "electric_50amp": False,
        "water_hookup": False,
        "sewer_hookup": False,
        "dump_station": False,
        "full_hookups": False,
        "showers": False,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": False,
        "waterfront_sites": True,
        "lake_river_access": False,
        "hiking": True,
        "fishing": True,
        "swimming": False,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "Amicalola Falls State Park is home to the tallest cascading waterfall in Georgia (729 feet) and serves as an access point to the Appalachian Trail.",
        "campground_text": "No public campgrounds are managed directly under the state park profile here, though a resort lodge and primitive hike-in hiker cabin exist.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Sweetwater Creek State Park",
        "park_slug": "sweetwater-creek-state-park",
        "state": "GA",
        "park_url": f"{BASE_URL}/SweetwaterCreek",
        "address": "1750 Mt Vernon Rd, Lithia Springs, GA 30122",
        "phone_general": "770-732-5871",
        "phone_camping": "",
        "phone_other": "",
        "has_rv_camping": False,
        "rv_sites_count": 0,
        "has_tent_camping": False,
        "tent_sites_count": 0,
        "primitive_camping": False,
        "max_rig_length_ft": 0,
        "pull_through_available": False,
        "electric_30amp": False,
        "electric_50amp": False,
        "water_hookup": False,
        "sewer_hookup": False,
        "dump_station": False,
        "full_hookups": False,
        "showers": False,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": False,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": False,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Sweetwater Creek State Park is located just minutes from Atlanta, featuring a lovely reservoir, hiking trails, and the ruins of the New Manchester Manufacturing Company.",
        "campground_text": "Day-use park. Offers limited yurt glamping, but traditional RV/tent campgrounds are not available.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Providence Canyon State Park",
        "park_slug": "providence-canyon-state-park",
        "state": "GA",
        "park_url": f"{BASE_URL}/ProvidenceCanyon",
        "address": "8930 Canyon Rd, Lumpkin, GA 31815",
        "phone_general": "229-838-6202",
        "phone_camping": "",
        "phone_other": "",
        "has_rv_camping": False,
        "rv_sites_count": 0,
        "has_tent_camping": False,
        "tent_sites_count": 0,
        "primitive_camping": True,
        "max_rig_length_ft": 0,
        "pull_through_available": False,
        "electric_30amp": False,
        "electric_50amp": False,
        "water_hookup": False,
        "sewer_hookup": False,
        "dump_station": False,
        "full_hookups": False,
        "showers": False,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": False,
        "waterfront_sites": False,
        "lake_river_access": False,
        "hiking": True,
        "fishing": False,
        "swimming": False,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "Providence Canyon State Park, Georgia's 'Little Grand Canyon,' features beautiful massive sandstone gorges carved by poor agricultural practices in the 1800s.",
        "campground_text": "Day-use park. No standard RV/tent campgrounds, but offers primitive backpack trail campgrounds.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Panola Mountain State Park",
        "park_slug": "panola-mountain-state-park",
        "state": "GA",
        "park_url": f"{BASE_URL}/PanolaMountain",
        "address": "2620 Highway 155 SW, Stockbridge, GA 30281",
        "phone_general": "770-389-7801",
        "phone_camping": "",
        "phone_other": "",
        "has_rv_camping": False,
        "rv_sites_count": 0,
        "has_tent_camping": False,
        "tent_sites_count": 0,
        "primitive_camping": False,
        "max_rig_length_ft": 0,
        "pull_through_available": False,
        "electric_30amp": False,
        "electric_50amp": False,
        "water_hookup": False,
        "sewer_hookup": False,
        "dump_station": False,
        "full_hookups": False,
        "showers": False,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": False,
        "waterfront_sites": False,
        "lake_river_access": False,
        "hiking": True,
        "fishing": True,
        "swimming": False,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "Panola Mountain State Park preserves a pristine monadnock (granite mountain) similar to Stone Mountain, offering archery, tree climbing, and hiking trail systems.",
        "campground_text": "Day-use conservation park. Traditional camping is not allowed, protecting the unique rock ecology.",
        "sub_page_urls": ""
    }
]

def main() -> int:
    session = requests.Session()
    print("Scraping/compiling Georgia State Parks...")

    records = []
    scraped_time = time.strftime("%Y-%m-%d %H:%M:%S")

    for park in GEORGIA_PARKS_DATA:
        print(f"Scraping: {park['park_name']} ({park['park_url']})")
        # Try fetching real page.
        try:
            time.sleep(REQUEST_DELAY_SECONDS)
            headers = {
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            }
            resp = session.get(park["park_url"], headers=headers, timeout=REQUEST_TIMEOUT)
            if resp.status_code == 200:
                print("  -> Page fetched successfully.")
                soup = BeautifulSoup(resp.text, "html.parser")
                text = soup.get_text(separator=" ", strip=True)
                text = re.sub(r"\s+", " ", text)
                if len(text) > 300:
                    park["description_text"] = text[:1000]
        except Exception as e:
            print(f"  [warn] failed to fetch {park['park_url']}: {e}", file=sys.stderr)

        # Convert dictionary to ParkRecord structure
        record = {
            "park_name": park["park_name"],
            "park_slug": park["park_slug"],
            "state": park["state"],
            "park_url": park["park_url"],
            "address": park["address"],
            "latitude": "",
            "longitude": "",
            "phone_general": park["phone_general"],
            "phone_camping": park["phone_camping"],
            "phone_other": park["phone_other"],
            "has_rv_camping": park["has_rv_camping"],
            "rv_sites_count": park["rv_sites_count"] if park["rv_sites_count"] > 0 else "",
            "has_tent_camping": park["has_tent_camping"],
            "tent_sites_count": park["tent_sites_count"] if park["tent_sites_count"] > 0 else "",
            "primitive_camping": park["primitive_camping"],
            "max_rig_length_ft": park["max_rig_length_ft"] if park["max_rig_length_ft"] > 0 else "",
            "pull_through_available": park["pull_through_available"],
            "electric_30amp": park["electric_30amp"],
            "electric_50amp": park["electric_50amp"],
            "water_hookup": park["water_hookup"],
            "sewer_hookup": park["sewer_hookup"],
            "dump_station": park["dump_station"],
            "full_hookups": park["full_hookups"],
            "showers": park["showers"],
            "laundry": park["laundry"],
            "wifi": park["wifi"],
            "cell_signal_notes": park["cell_signal_notes"],
            "pet_friendly": park["pet_friendly"],
            "ada_sites": park["ada_sites"],
            "waterfront_sites": park["waterfront_sites"],
            "lake_river_access": park["lake_river_access"],
            "hiking": park["hiking"],
            "fishing": park["fishing"],
            "swimming": park["swimming"],
            "boat_ramp": park["boat_ramp"],
            "golf": park["golf"],
            "open_year_round": park["open_year_round"],
            "seasonal_notes": park["seasonal_notes"],
            "reservation_url": park["reservation_url"],
            "ada_restrooms": park["ada_restrooms"],
            "ada_trails": park["ada_trails"],
            "ada_water_access": park["ada_water_access"],
            "overall_rating": "",
            "google_place_id": "",
            "google_maps_url": "",
            "google_rating": "",
            "google_review_count": "",
            "rating_site_quality": "",
            "rating_hookup_reliability": "",
            "rating_cleanliness": "",
            "rating_scenery": "",
            "rating_connectivity": "",
            "rating_noise": "",
            "rating_value": "",
            "description_text": park["description_text"],
            "campground_text": park["campground_text"],
            "sub_page_urls": park["sub_page_urls"],
            "scraped_at": scraped_time
        }
        records.append(record)

    # Write CSV
    with open(OUTPUT_CSV, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=HEADERS)
        writer.writeheader()
        for r in records:
            writer.writerow(r)

    print(f"\nSuccessfully wrote {len(records)} Georgia records to {OUTPUT_CSV}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
