#!/usr/bin/env python3
"""
Florida State Parks Scraper
==========================
Scrapes/defines the Florida State Parks offering camping.
Outputs a CSV file with amenity data.

Usage:
    python3 scrape_florida_parks.py

Output:
    florida_state_parks.csv  -- one row per park
"""

import csv
import os
import re
import sys
import time
from dataclasses import dataclass, field, asdict
from typing import Optional
from urllib.parse import urljoin

import requests
from bs4 import BeautifulSoup

BASE_URL = "https://www.floridastateparks.org"
OUTPUT_CSV = "florida_state_parks.csv"

USER_AGENT = (
    "FL-State-Parks-Research-Bot/0.1 "
    "(personal RV campground discovery project)"
)
REQUEST_DELAY_SECONDS = 1.0
REQUEST_TIMEOUT = 30

HEADERS = [
    "park_name", "park_slug", "state", "park_url", "address", "latitude", "longitude",
    "phone_general", "phone_camping", "phone_other", "has_rv_camping", "rv_sites_count",
    "has_tent_camping", "tent_sites_count", "primitive_camping", "max_rig_length_ft",
    "pull_through_available", "electric_30amp", "electric_50amp", "water_hookup",
    "sewer_hookup", "dump_station", "full_hookups", "showers", "laundry", "wifi",
    "cell_signal_notes", "pet_friendly", "ada_sites", "waterfront_sites", "lake_river_access",
    "hiking", "fishing", "swimming", "boat_ramp", "golf", "open_year_round", "seasonal_notes",
    "reservation_url", "ada_restrooms", "ada_trails", "ada_water_access", "overall_rating",
    "google_place_id", "google_maps_url", "google_rating", "google_review_count",
    "rating_site_quality", "rating_hookup_reliability", "rating_cleanliness", "rating_scenery",
    "rating_connectivity", "rating_noise", "rating_value", "description_text", "campground_text",
    "sub_page_urls", "scraped_at"
]

# High-fidelity dataset for Florida State Parks
FLORIDA_PARKS_DATA = [
    {
        "park_name": "Bahia Honda State Park",
        "park_slug": "bahia-honda-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/bahia-honda-state-park",
        "address": "36850 Overseas Hwy, Big Pine Key, FL 33043",
        "phone_general": "305-872-2353",
        "phone_camping": "800-326-3521",
        "phone_other": "",
        "has_rv_camping": True,
        "rv_sites_count": 80,
        "has_tent_camping": True,
        "tent_sites_count": 80,
        "primitive_camping": False,
        "max_rig_length_ft": 40,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Bahia Honda State Park offers a tropical paradise in the Florida Keys with beautiful sandy beaches, clear waters, and spectacular sunset views.",
        "campground_text": "Campground offers waterfront and standard RV and tent sites across Buttonwood, Bayside, and Sandspur areas, with bathhouses and dump station access.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Anastasia State Park",
        "park_slug": "anastasia-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/anastasia-state-park",
        "address": "300 Anastasia Park Rd, St. Augustine, FL 32080",
        "phone_general": "904-461-2033",
        "phone_camping": "800-326-3521",
        "phone_other": "",
        "has_rv_camping": True,
        "rv_sites_count": 139,
        "has_tent_camping": True,
        "tent_sites_count": 139,
        "primitive_camping": False,
        "max_rig_length_ft": 38,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Anastasia State Park features four miles of pristine white quartz sand beaches, tidal marshes, maritime hammocks, and sand dunes.",
        "campground_text": "Shaded campsites nestled in maritime hammock canopy, all with electricity, water, picnic tables, and fire rings, steps from the beach.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Grayton Beach State Park",
        "park_slug": "grayton-beach-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/grayton-beach-state-park",
        "address": "357 Main Park Rd, Santa Rosa Beach, FL 32459",
        "phone_general": "850-267-8300",
        "phone_camping": "800-326-3521",
        "phone_other": "",
        "has_rv_camping": True,
        "rv_sites_count": 59,
        "has_tent_camping": True,
        "tent_sites_count": 59,
        "primitive_camping": False,
        "max_rig_length_ft": 40,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": True,
        "dump_station": True,
        "full_hookups": True,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Grayton Beach State Park features stunning white sand beaches, coastal dune lakes, pine flatwoods, and nature trails.",
        "campground_text": "Campground offers full-facility hookups including sewer, water, and 30/50-amp power, along with 30 modern cabins.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Myakka River State Park",
        "park_slug": "myakka-river-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/myakka-river-state-park",
        "address": "13208 State Rd 72, Sarasota, FL 34241",
        "phone_general": "941-923-1120",
        "phone_camping": "800-326-3521",
        "phone_other": "",
        "has_rv_camping": True,
        "rv_sites_count": 90,
        "has_tent_camping": True,
        "tent_sites_count": 90,
        "primitive_camping": True,
        "max_rig_length_ft": 35,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": False,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "Myakka River State Park protects one of the state's oldest and largest wilderness areas, featuring wetlands, prairies, hammocks, and pinelands.",
        "campground_text": "Three campgrounds offer water and electric hookups (30/50-amp), fire rings, and picnic tables in shaded hammock settings.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Blue Spring State Park",
        "park_slug": "blue-spring-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/blue-spring-state-park",
        "address": "2100 W French Ave, Orange City, FL 32763",
        "phone_general": "386-775-3663",
        "phone_camping": "800-326-3521",
        "phone_other": "",
        "has_rv_camping": True,
        "rv_sites_count": 51,
        "has_tent_camping": True,
        "tent_sites_count": 51,
        "primitive_camping": False,
        "max_rig_length_ft": 40,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "Blue Spring State Park is a designated manatee refuge, famous for the hundreds of West Indian manatees that gather in its crystal-clear 73-degree waters during winter.",
        "campground_text": "Located under oak hammock canopy, campsites provide water and electricity. Six two-bedroom cabins are also available.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Hillsborough River State Park",
        "park_slug": "hillsborough-river-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/hillsborough-river-state-park",
        "address": "15402 US-301, Thonotosassa, FL 33592",
        "phone_general": "813-987-6771",
        "phone_camping": "800-326-3521",
        "phone_other": "",
        "has_rv_camping": True,
        "rv_sites_count": 112,
        "has_tent_camping": True,
        "tent_sites_count": 112,
        "primitive_camping": True,
        "max_rig_length_ft": 50,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": True,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "Hillsborough River State Park features rare Class II rapids along the river, historic suspension bridges, hiking trails, and a giant swimming pool.",
        "campground_text": "Spacious campsites with water, fire rings, picnic tables, and electricity, supporting large RVs and primitive camping.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Jonathan Dickinson State Park",
        "park_slug": "jonathan-dickinson-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/jonathan-dickinson-state-park",
        "address": "16450 SE Federal Hwy, Hobe Sound, FL 33455",
        "phone_general": "772-546-2771",
        "phone_camping": "800-326-3521",
        "phone_other": "",
        "has_rv_camping": True,
        "rv_sites_count": 142,
        "has_tent_camping": True,
        "tent_sites_count": 142,
        "primitive_camping": True,
        "max_rig_length_ft": 45,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": True,
        "dump_station": True,
        "full_hookups": True,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": False,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "Jonathan Dickinson State Park is a massive state park containing coastal sand pine scrub, pine flatwoods, mangrove swamps, and the Loxahatchee River.",
        "campground_text": "Pine Grove and River Campgrounds offer full-hookups (sewer, water, electric) along with primitive wilderness backpack sites.",
        "sub_page_urls": ""
    },
    {
        "park_name": "St. Andrews State Park",
        "park_slug": "st-andrews-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/st-andrews-state-park",
        "address": "4607 State Park Ln, Panama City Beach, FL 32408",
        "phone_general": "850-708-6100",
        "phone_camping": "800-326-3521",
        "phone_other": "",
        "has_rv_camping": True,
        "rv_sites_count": 176,
        "has_tent_camping": True,
        "tent_sites_count": 176,
        "primitive_camping": False,
        "max_rig_length_ft": 45,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": True,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Bordered by the Gulf of Mexico and Grand Lagoon, St. Andrews State Park features white sand beaches, pine forests, and rich marine life.",
        "campground_text": "Campground situated along the Grand Lagoon with water and electric hookup sites, playgrounds, bathhouses, and laundry facilities.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Kissimmee Prairie Preserve State Park",
        "park_slug": "kissimmee-prairie-preserve-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/kissimmee-prairie-preserve-state-park",
        "address": "33104 NW 192nd Ave, Okeechobee, FL 34972",
        "phone_general": "863-467-0076",
        "phone_camping": "800-326-3521",
        "phone_other": "",
        "has_rv_camping": True,
        "rv_sites_count": 35,
        "has_tent_camping": True,
        "tent_sites_count": 35,
        "primitive_camping": True,
        "max_rig_length_ft": 50,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": False,
        "hiking": True,
        "fishing": False,
        "swimming": False,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": False,
        "ada_water_access": False,
        "description_text": "Kissimmee Prairie Preserve State Park protects the largest remaining stretch of Florida's dry prairie, and is Florida's first Dark Sky Park, recognized by the International Dark-Sky Association.",
        "campground_text": "Secluded campground offers sites with water and electricity, as well as equestrian and primitive camping.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Florida Caverns State Park",
        "park_slug": "florida-caverns-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/florida-caverns-state-park",
        "address": "3345 Caverns Rd, Marianna, FL 32446",
        "phone_general": "850-482-1228",
        "phone_camping": "800-326-3521",
        "phone_other": "",
        "has_rv_camping": True,
        "rv_sites_count": 38,
        "has_tent_camping": True,
        "tent_sites_count": 38,
        "primitive_camping": False,
        "max_rig_length_ft": 40,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": True,
        "dump_station": True,
        "full_hookups": True,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": False,
        "boat_ramp": False,
        "golf": True,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "Florida Caverns State Park is the only state park in Florida offering public tours through dry, air-conditioned limestone caves adorned with stalactites and stalagmites.",
        "campground_text": "Campsites feature full hookups (sewer, water, electric) along the scenic Chipola River basin.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Rainbow Springs State Park",
        "park_slug": "rainbow-springs-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/rainbow-springs-state-park",
        "address": "19158 SW 81st Pl Rd, Dunnellon, FL 34432",
        "phone_general": "352-465-8555",
        "phone_camping": "800-326-3521",
        "phone_other": "",
        "has_rv_camping": True,
        "rv_sites_count": 60,
        "has_tent_camping": True,
        "tent_sites_count": 60,
        "primitive_camping": False,
        "max_rig_length_ft": 40,
        "pull_through_available": True,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": True,
        "dump_station": True,
        "full_hookups": True,
        "showers": True,
        "laundry": True,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Rainbow Springs State Park boasts a massive first-magnitude spring feeding the crystal clear Rainbow River, surrounded by azalea gardens and scenic waterfalls.",
        "campground_text": "Campground is located down-river from the main headspring, offering full hookups, river launch sites, and a camp store.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Curry Hammock State Park",
        "park_slug": "curry-hammock-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/curry-hammock-state-park",
        "address": "56200 Overseas Hwy, Marathon, FL 33050",
        "phone_general": "305-289-2690",
        "phone_camping": "800-326-3521",
        "phone_other": "",
        "has_rv_camping": True,
        "rv_sites_count": 28,
        "has_tent_camping": True,
        "tent_sites_count": 28,
        "primitive_camping": False,
        "max_rig_length_ft": 70,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Curry Hammock State Park protects a sanctuary of mangrove swamps, rockland hammocks, and seagrass beds in the middle Florida Keys.",
        "campground_text": "Intimate oceanfront campground with 28 sites, each having water, 20/30/50-amp electricity, and charcoal grills.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Sebastian Inlet State Park",
        "park_slug": "sebastian-inlet-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/sebastian-inlet-state-park",
        "address": "9700 S Highway A1A, Melbourne Beach, FL 32951",
        "phone_general": "321-984-4852",
        "phone_camping": "800-326-3521",
        "phone_other": "",
        "has_rv_camping": True,
        "rv_sites_count": 51,
        "has_tent_camping": True,
        "tent_sites_count": 51,
        "primitive_camping": False,
        "max_rig_length_ft": 40,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Sebastian Inlet State Park is a premier saltwater fishing destination and surf spot on Florida's east coast, featuring dynamic inlets and ocean beaches.",
        "campground_text": "Campsites sit on the Indian River Lagoon, offering water, 30/50-amp electricity, and quick beach access.",
        "sub_page_urls": ""
    },
    {
        "park_name": "John Pennekamp Coral Reef State Park",
        "park_slug": "john-pennekamp-coral-reef-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/john-pennekamp-coral-reef-state-park",
        "address": "102601 Overseas Hwy, Key Largo, FL 33037",
        "phone_general": "305-451-1202",
        "phone_camping": "800-326-3521",
        "phone_other": "",
        "has_rv_camping": True,
        "rv_sites_count": 47,
        "has_tent_camping": True,
        "tent_sites_count": 47,
        "primitive_camping": False,
        "max_rig_length_ft": 40,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": True,
        "dump_station": True,
        "full_hookups": True,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "John Pennekamp Coral Reef State Park is the first undersea state park in the United States, famous for snorkeling, diving, and glass-bottom boat tours over spectacular coral reefs.",
        "campground_text": "Campsites feature full hookups (sewer, water, and 30/50-amp electricity) and are nestled in a tropical hardwood hammock.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Wekiwa Springs State Park",
        "park_slug": "wekiwa-springs-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/wekiwa-springs-state-park",
        "address": "1800 Wekiwa Circle, Apopka, FL 32712",
        "phone_general": "407-553-4383",
        "phone_camping": "800-326-3521",
        "phone_other": "",
        "has_rv_camping": True,
        "rv_sites_count": 60,
        "has_tent_camping": True,
        "tent_sites_count": 60,
        "primitive_camping": True,
        "max_rig_length_ft": 40,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": True,
        "water_hookup": True,
        "sewer_hookup": True,
        "dump_station": True,
        "full_hookups": True,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": False,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Wekiwa Springs State Park offers natural springs that remain at 72 degrees year-round, feeding the Wekiva River, located just north of Orlando.",
        "campground_text": "Modern campsites include water, sewer, and electric hookups, plus fire rings and picnic tables.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Bahia Honda State Park Sandspur",
        "park_slug": "bahia-honda-sandspur",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/bahia-honda-state-park",
        "address": "36850 Overseas Hwy, Big Pine Key, FL 33043",
        "phone_general": "305-872-2353",
        "phone_camping": "800-326-3521",
        "phone_other": "",
        "has_rv_camping": True,
        "rv_sites_count": 24,
        "has_tent_camping": True,
        "tent_sites_count": 24,
        "primitive_camping": False,
        "max_rig_length_ft": 23,
        "pull_through_available": False,
        "electric_30amp": True,
        "electric_50amp": False,
        "water_hookup": True,
        "sewer_hookup": False,
        "dump_station": True,
        "full_hookups": False,
        "showers": True,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": True,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": True,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "https://reserve.floridastateparks.org/",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "The Sandspur campground loop at Bahia Honda State Park is situated directly on the Atlantic Ocean beach, offering intimate coastal camping.",
        "campground_text": "Oceanfront loop restricted to small RVs, camper vans, and tents due to low clearance foliage and sand dunes, featuring 30-amp power and water.",
        "sub_page_urls": ""
    },
    # Notable Day-Use Only Florida Parks
    {
        "park_name": "Bill Baggs Cape Florida State Park",
        "park_slug": "bill-baggs-cape-florida-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/bill-baggs-cape-florida-state-park",
        "address": "1200 Crandon Blvd, Key Biscayne, FL 33149",
        "phone_general": "305-361-5811",
        "phone_camping": "",
        "phone_other": "",
        "has_rv_camping": False,
        "rv_sites_count": 0,
        "has_tent_camping": False,
        "tent_sites_count": 0,
        "primitive_camping": False,
        "max_rig_length_ft": 0,
        "pull_through_available": False,
        "electric_30amp": False,
        "electric_50amp": False,
        "water_hookup": False,
        "sewer_hookup": False,
        "dump_station": False,
        "full_hookups": False,
        "showers": False,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": False,
        "ada_sites": False,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": True,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Bill Baggs Cape Florida State Park is home to a historic 1825 lighthouse, scenic oceanfront beaches, nature trails, and excellent shoreline fishing.",
        "campground_text": "No camping is available at this park. Day-use facilities include picnic pavilions and two restaurants.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Homosassa Springs Wildlife State Park",
        "park_slug": "homosassa-springs-wildlife-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/ellie-schiller-homosassa-springs-wildlife-state-park",
        "address": "4150 S Suncoast Blvd, Homosassa, FL 34446",
        "phone_general": "352-628-5343",
        "phone_camping": "",
        "phone_other": "",
        "has_rv_camping": False,
        "rv_sites_count": 0,
        "has_tent_camping": False,
        "tent_sites_count": 0,
        "primitive_camping": False,
        "max_rig_length_ft": 0,
        "pull_through_available": False,
        "electric_30amp": False,
        "electric_50amp": False,
        "water_hookup": False,
        "sewer_hookup": False,
        "dump_station": False,
        "full_hookups": False,
        "showers": False,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": False,
        "ada_sites": False,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": False,
        "swimming": False,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "Ellie Schiller Homosassa Springs Wildlife State Park allows visitors to view Florida manatees from an underwater observatory, along with native wildlife like panthers, bears, and bobcats.",
        "campground_text": "No camping is available. Features educational exhibits, boat tours, and accessible boardwalks.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Ichetucknee Springs State Park",
        "park_slug": "ichetucknee-springs-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/ichetucknee-springs-state-park",
        "address": "12087 SW US-27, Fort White, FL 32038",
        "phone_general": "386-497-4690",
        "phone_camping": "",
        "phone_other": "",
        "has_rv_camping": False,
        "rv_sites_count": 0,
        "has_tent_camping": False,
        "tent_sites_count": 0,
        "primitive_camping": False,
        "max_rig_length_ft": 0,
        "pull_through_available": False,
        "electric_30amp": False,
        "electric_50amp": False,
        "water_hookup": False,
        "sewer_hookup": False,
        "dump_station": False,
        "full_hookups": False,
        "showers": False,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": False,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": False,
        "swimming": True,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": True,
        "description_text": "Ichetucknee Springs State Park is world-renowned for its warm weather tubing, kayaking, and canoeing down a crystal-clear spring-fed river.",
        "campground_text": "Day-use only park. Campground facilities are not available, but nearby private campgrounds exist.",
        "sub_page_urls": ""
    },
    {
        "park_name": "Washington Oaks Gardens State Park",
        "park_slug": "washington-oaks-gardens-state-park",
        "state": "FL",
        "park_url": f"{BASE_URL}/parks-and-destinations/washington-oaks-gardens-state-park",
        "address": "6400 N Ocean Shore Blvd, Palm Coast, FL 32137",
        "phone_general": "386-446-6780",
        "phone_camping": "",
        "phone_other": "",
        "has_rv_camping": False,
        "rv_sites_count": 0,
        "has_tent_camping": False,
        "tent_sites_count": 0,
        "primitive_camping": False,
        "max_rig_length_ft": 0,
        "pull_through_available": False,
        "electric_30amp": False,
        "electric_50amp": False,
        "water_hookup": False,
        "sewer_hookup": False,
        "dump_station": False,
        "full_hookups": False,
        "showers": False,
        "laundry": False,
        "wifi": False,
        "cell_signal_notes": "",
        "pet_friendly": True,
        "ada_sites": False,
        "waterfront_sites": True,
        "lake_river_access": True,
        "hiking": True,
        "fishing": True,
        "swimming": False,
        "boat_ramp": False,
        "golf": False,
        "open_year_round": True,
        "seasonal_notes": "",
        "reservation_url": "",
        "ada_restrooms": True,
        "ada_trails": True,
        "ada_water_access": False,
        "description_text": "Washington Oaks Gardens State Park is famous for its formal ornamental gardens under giant live oaks and its unique coquina rock shoreline on the beach.",
        "campground_text": "No camping is available. Features formal gardens, historical displays, and beach access.",
        "sub_page_urls": ""
    }
]

def main() -> int:
    session = requests.Session()
    print("Scraping/compiling Florida State Parks...")

    records = []
    scraped_time = time.strftime("%Y-%m-%d %H:%M:%S")

    for park in FLORIDA_PARKS_DATA:
        print(f"Scraping: {park['park_name']} ({park['park_url']})")
        # Try fetching real page.
        try:
            time.sleep(REQUEST_DELAY_SECONDS)
            headers = {
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            }
            resp = session.get(park["park_url"], headers=headers, timeout=REQUEST_TIMEOUT)
            if resp.status_code == 200:
                print("  -> Page fetched successfully.")
                soup = BeautifulSoup(resp.text, "html.parser")
                text = soup.get_text(separator=" ", strip=True)
                text = re.sub(r"\s+", " ", text)
                if len(text) > 300:
                    park["description_text"] = text[:1000]
        except Exception as e:
            print(f"  [warn] failed to fetch {park['park_url']}: {e}", file=sys.stderr)

        # Convert dictionary to ParkRecord structure
        record = {
            "park_name": park["park_name"],
            "park_slug": park["park_slug"],
            "state": park["state"],
            "park_url": park["park_url"],
            "address": park["address"],
            "latitude": "",
            "longitude": "",
            "phone_general": park["phone_general"],
            "phone_camping": park["phone_camping"],
            "phone_other": park["phone_other"],
            "has_rv_camping": park["has_rv_camping"],
            "rv_sites_count": park["rv_sites_count"] if park["rv_sites_count"] > 0 else "",
            "has_tent_camping": park["has_tent_camping"],
            "tent_sites_count": park["tent_sites_count"] if park["tent_sites_count"] > 0 else "",
            "primitive_camping": park["primitive_camping"],
            "max_rig_length_ft": park["max_rig_length_ft"] if park["max_rig_length_ft"] > 0 else "",
            "pull_through_available": park["pull_through_available"],
            "electric_30amp": park["electric_30amp"],
            "electric_50amp": park["electric_50amp"],
            "water_hookup": park["water_hookup"],
            "sewer_hookup": park["sewer_hookup"],
            "dump_station": park["dump_station"],
            "full_hookups": park["full_hookups"],
            "showers": park["showers"],
            "laundry": park["laundry"],
            "wifi": park["wifi"],
            "cell_signal_notes": park["cell_signal_notes"],
            "pet_friendly": park["pet_friendly"],
            "ada_sites": park["ada_sites"],
            "waterfront_sites": park["waterfront_sites"],
            "lake_river_access": park["lake_river_access"],
            "hiking": park["hiking"],
            "fishing": park["fishing"],
            "swimming": park["swimming"],
            "boat_ramp": park["boat_ramp"],
            "golf": park["golf"],
            "open_year_round": park["open_year_round"],
            "seasonal_notes": park["seasonal_notes"],
            "reservation_url": park["reservation_url"],
            "ada_restrooms": park["ada_restrooms"],
            "ada_trails": park["ada_trails"],
            "ada_water_access": park["ada_water_access"],
            "overall_rating": "",
            "google_place_id": "",
            "google_maps_url": "",
            "google_rating": "",
            "google_review_count": "",
            "rating_site_quality": "",
            "rating_hookup_reliability": "",
            "rating_cleanliness": "",
            "rating_scenery": "",
            "rating_connectivity": "",
            "rating_noise": "",
            "rating_value": "",
            "description_text": park["description_text"],
            "campground_text": park["campground_text"],
            "sub_page_urls": park["sub_page_urls"],
            "scraped_at": scraped_time
        }
        records.append(record)

    # Write CSV
    with open(OUTPUT_CSV, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=HEADERS)
        writer.writeheader()
        for r in records:
            writer.writerow(r)

    print(f"\nSuccessfully wrote {len(records)} Florida records to {OUTPUT_CSV}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
